charts/internal/aws-infra/templates/main.tf, charts/internal/aws-infra/values.yaml, docs/usage-as-end-user.md, example/30-infrastructure.yaml, hack/api-reference/api.md, pkg/apis/aws/types_infrastructure.go, pkg/apis/aws/v1alpha1/types_infrastructure.go, pkg/apis/aws/v1alpha1/zz_generated.conversion.go, pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go, pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go, pkg/apis/aws/zz_generated.deepcopy.go, pkg/controller/infrastructure/actuator_reconcile.go
Allow adding gateway endpoints to the VPC of an AWS cluster. Example for adding an endpoint for S3:
```yaml
apiVersion: core.gardener.cloud/v1alpha1
kind: Shoot
spec:
provider:
type: aws
infrastructureConfig:
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
vpc:
gatewayEndpoints:
- "s3"
```
More info about gateway endpoints
https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html
Relevant terraform resource
https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html
```improvement operator
Now it is possible to define VPC Gateway Endpoints for AWS shoots. The new list "gatewayEdnpoints" inside "vpc" sections is a list endpoint service names. Each item is mapped to a vpc …
```
=> allow adding gateway endpoints to vpc

charts/images.yaml
``` noteworthy operator github.com/gardener/machine-controller-manager #408 @hardikdr
Bugfix: Set deleteOnTermination to true by default for volumes. Disks that are created with the instance are deleted with instance termination.
```
=> [ci:component:github.com/gardener/machine-controller-manager:v0.26.1->v0.26.2]

pkg/validator/shoot_handler.go, pkg/validator/shoot_validator.go
Only validate zones in `InfrastructureConfig` against zones in `CloudProfile` when:
a) Shoot is created
b) Zones in `InfrastructureConfig` are updated
This ensures that already running shoots won't break after a zone is removed from a cloud profile.
/cc @rfranzke.
I'll also file a PR for g/g's worker validation:
https://github.com/gardener/gardener/blob/master/plugin/pkg/shoot/validator/admission.go#L433-L440
```improvement operator
The AWS validator only validates configured zones in the `InfrastructureConfig` against available zones in the referring `CloudProfile` when shoots are created or the zone information in `InfrastructureConfig` is updated. This prevent immediate breakage of already …
```
=> Restrict cross validation for infra config and cloud profile

charts/images.yaml
``` improvement operator github.com/gardener/machine-controller-manager #409 @prashanth26
Set deleteOnTermination flag to true while deleting the VMs in AWS.
```
=> [ci:component:github.com/gardener/machine-controller-manager:v0.26.2->v0.26.3]

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
Allow defining zones multiple times in infraConfig.
/cc @rfranzke @hoeltcl 
```improvement operator
The AWS validator now allows a zone being specified multiple times in the `InfrastructureConfig`.
```
=> Allow defining zones multiple times in infraConfig

charts/internal/aws-infra/templates/main.tf
Increase create timeout for aws_route.private_utility_zX_nat.
Ref https://github.com/gardener/gardener-extension-provider-aws/issues/5
```improvement operator
The create timeout for `aws_route.private_utility_zX_nat` is now increased to `5m`.
```
=> Increase create timeout for aws_route.private_utility_zX_nat

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
Continues https://github.com/gardener/gardener-extension-provider-aws/pull/17
Currently the whole VPC section is immutable although gateway endpoints should be mutable. The change makes the immutable check more specific to `vpc.id` and `vpc.cidr`, and leaves `gatewayEndpoints` as a mutable field.
```improvement operator
Now it is possible to modify the gateway endpoints list `networks.vpc.gatewayEndpoints` after the shoot is created.
```
=> allow modifying gateway endpoints inside vpc after shoot creation

pkg/controller/worker/machines.go
fix nil pointer when applying machine class chart
Related https://github.com/gardener/gardener/pull/2037
```improvement developer
Fix nil pointer when applying machine class chart
```
=> fix nil pointer when applying machine class chart

charts/images.yaml
``` improvement operator github.com/gardener/cloud-provider-aws #2 @ialidzhikov 
`k8s.io/legacy-cloud-providers` is now updated to `v0.17.4`.
```
=> [ci:component:github.com/gardener/cloud-provider-aws:v1.17.0->v1.17.4]

charts/images.yaml
```improvement operator github.com/gardener/cloud-provider-aws $87ca4e44cdf0d71377d4ce93d87241d509980e33
`k8s.io/legacy-cloud-providers` is now updated to `v1.18.0`.
```
=> [ci:component:github.com/gardener/cloud-provider-aws:v1.17.4->v1.18.0]

charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/vpa.yaml
Currently VPA can update the container memory request to be < 4MB which is not allowed by docker (ref https://docs.docker.com/config/containers/resource_constraints/)
```yaml
name: csi-attacher
resources:
limits:
cpu: 30m
memory: 3200Ki
requests:
cpu: 10m
memory: "2097152"
```
Similar container fails with:
```
$ k -n shoot--foo--bar get po | grep CreateContainerError
csi-driver-controller-7454d974c8-mvdx9        5/6     CreateContainerError   0          25m
$ k -n shoot--foo--bar describe po csi-driver-controller-7454d974c8-mvdx9
Warning  Failed     23m (x2 over 24m)    kubelet, ip-10-242-31-64.eu-west-1.compute.internal  Error: Error response from daemon: Minimum memory limit allowed is 4MB
```
There is also …
=> Set minAllowed memory for csi containers

docs/usage-as-end-user.md
Add documentation for `aws.provider.extensions.gardener.cloud/v1lalpha1.WorkerConfig`.
```improvement user
Documentation how to use `WorkerConfig` (e.g., to set the `iops` for `io1` volumes) has been added to https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage-as-end-user.md.
```
=> Add documentation for WorkerConfig

hack/api-reference/api.md, pkg/apis/aws/types_worker.go, pkg/apis/aws/v1alpha1/types_worker.go, pkg/apis/aws/validation/shoot.go, pkg/apis/aws/validation/shoot_test.go, pkg/apis/aws/validation/worker.go, pkg/apis/aws/validation/worker_test.go
If no `iops` are set when `io1` volumes are used then we should return an error in the validation of the `Shoot`, otherwise the `Worker` controller will fail, eventually, because MCM will complain:
```
E0423 11:13:31.849445       1 awsmachineclass.go:126] Validation of AWSMachineClass failed spec.blockDevices[0].ebs.iops: Required value: Please mention a valid ebs volume iops
```
/kind bug
```improvement user
When worker pools with the `io1` volume type are used then the validation does now enforce that the `.spec.provider.workers[].providerConfig` does contain a proper AWS `WorkerConfig` (that states the iops).
```
=> Enforce workerConfig for io1 volumes

charts/internal/machineclass/templates/machineclass.yaml, charts/internal/machineclass/values.yaml, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
This PR adds the zone information label to the `AWSMachineClass` to allow the cluster-autoscaler scaling to/from zero.
Fixes #77
/cc @hardikdr @prashanth26 
```improvement user
NONE
```
=> Add zone label to machine classes

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller-deployment.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
Scale down csi-snapshot-controller when the Shoot is hibernated.
Fixes #
```improvement operator
NONE
```
=> Scale down csi-snapshot-controller when the Shoot is hibernated

charts/images.yaml
Update kubernetes-csi/external-snapshotter to v2.1.1.
Fixes #
```improvement operator
`kubernetes-csi/external-snapshotter` components are updated to `v2.1.1`.
```
=> Update kubernetes-csi/external-snapshotter to v2.1.1

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
Like PR https://github.com/gardener/gardener-extension-provider-gcp/pull/90
This PR will add worker pool labels to AWS EC2, with this feature we can add custom labels to AWS EC2
Fixes # 
No issue is opened, but there is one GCP issue https://github.com/gardener/gardener-extension-provider-gcp/issues/82
```improvement operator
WorkerPool labels will be added to  AWS EC2 as the VM tag
```
=> Support add custom tags on AWS EC2

charts/internal/aws-infra/templates/main.tf, pkg/controller/infrastructure/actuator_delete.go, pkg/controller/infrastructure/actuator_reconcile.go
With this PR we add some timeouts for those Terraform resources that are supporting it. Also, we will no longer requeue with the constant `30s` on errors but leverage the exponential backoff functionality of the underlying workqueue.
Part of gardener/gardener#2253
```improvement operator
NONE
```
=> Use Terraform resource timeouts and workqueue backoff

pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/infrastructure/actuator_restore.go, test/integration/infrastructure/infrastructure_test.go
Prevent errors to be logged multiple times.
Ref gardener/gardener#2325
```improvement operator
NONE
```
=> Prevent errors to be logged multiple times

charts/images.yaml
```improvement operator github.com/gardener/cloud-provider-aws #3 @ialidzhikov
`k8s.io/legacy-cloud-providers` is now updated to `v0.18.3`.
```
=> Upgrade github.com/gardener/cloud-provider-aws

cmd/gardener-extension-provider-aws/app/app.go, go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/controller.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go, vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go, vendor/modules.txt
/platform aws
Vendor gardener/gardener@4f4a1db77d90a828d5681ee4a7daab9a920ed3af
```improvement operator
`ClusterRole`s for the machine-controller-manager that might be orphaned now as they created with an earlier, buggy version of this controller are now cleaned up during startup.
```
=> Vendor gardener/gardener@28def0ceecf15f5c7323cd5e65300adc0b0c81da

docs/usage-as-end-user.md, example/30-worker.yaml, pkg/apis/aws/validation/shoot.go, pkg/apis/aws/validation/shoot_test.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area storage
/platform aws
After https://github.com/gardener/gardener/pull/1893 was merged quite some time ago, this PR now adds support for the AWS extension to handle multiple EBS disks for the worker machines. Additionally, it now supports configuring them for encryption.
Ref https://github.com/gardener/machine-controller-manager/issues/462
Ref https://github.com/gardener/gardener/issues/2354
* Thanks @guydaichs for your work and contributions!
* For now, the `.volume.iops` in the `WorkerConfig` would be only applied to the root disk. In a follow-up PR I'll make it configurable per volume. …
=> Support multiple EBS disks and encryption when creating machines

charts/internal/aws-infra/templates/main.tf, charts/internal/aws-infra/templates/variables.tf, charts/internal/aws-infra/values.yaml, pkg/controller/infrastructure/actuator_reconcile.go
/kind cleanup
/platform aws
With https://github.com/gardener-attic/gardener-extensions/pull/336 , we adapted our terraform configuration to be v0.12 compatible preserving the v0.11 compatibility.
There are major changes introduced in the terraform language with v0.12 and terraform v0.12 is backwards-compatible accepting also terraform v0.11 configuration.
Starting from `v0.12.14`, terraform is emitting deprecation warning when old form is being used:
```
Warning: Interpolation-only expressions are deprecated
on tf/main.tf line 2, in provider "aws":
2:   access_key = "${var.ACCESS_KEY_ID}"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this …
```
=> Adapt to terrafom v0.12 language changes

pkg/apis/aws/validation/shoot.go, pkg/apis/aws/validation/shoot_test.go
/area quality
/kind bug
/platform aws
Currently validator-aws panics when the worker has no providerConfig.
```
{"level":"info","ts":"2020-06-09T07:16:12.321Z","logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
2020/06/09 07:16:15 http: panic serving 10.40.0.177:52956: runtime error: invalid memory address or nil pointer dereference
goroutine 272 [running]:
net/http.(*conn).serve.func1(0xc0001d3720)
/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x18ca8e0, 0x2b412a0)
/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/gardener/gardener-extension-provider-aws/pkg/apis/aws/validation.ValidateWorkerConfig(0x0, 0xc000884a50, 0x0, 0x0, 0x0, 0xc0008bb410, …
```
=> Prevent panic when the worker has no providerConfig

pkg/aws/client/client.go
Signed-off-by: Swapnil Mhamane <swapnil.mhamane@sap.com>
/area security
/priority critical
/platform aws
This PR configures the bucket with SSE encryption
Fixes #
```improvement operator
Server side encryption will be enabled for provisioned s3 buckets.
```
=> :sparkle: Enable default SSE for s3 bucket

charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml
/kind bug
/platform aws
Removes the `NoExecute` toleration from components running in the Seed cluster, such as the CCM. This toleration should not be needed for such components, see the discussion in https://github.com/gardener/gardener-extension-provider-azure/pull/120.
```improvement operator
NONE
```
=> Remove NoExecute toleration from CCM and LB readvertiser

README.md
/platform aws
Specify that v1.10 and v1.11 are no longer actively tested
```improvement operator
NONE
```
=> Specify that v1.10 and v1.11 are no longer actively tested

charts/internal/aws-infra/templates/main.tf
/area security
/kind cleanup
/platform aws
IAM Instance profiles are not needed for bastions as they should only be used as jump hosts.
Fixes #4
PR in https://github.com/gardener/gardenctl/pull/218 which removes the instance profile when launching such machines. Only `gardenctl` versions which have https://github.com/gardener/gardenctl/pull/218 can be used to create instances once this PR is merged.
```noteworthy operator
IAM roles, policies and instance profiles for bastion instances are no longer created and existing ones are removed during the next infra reconciliation.
```
```action operator …
```
=> Remove bastion IAM role, profiles and policies

test/integration/infrastructure/infrastructure_test.go
/kind bug
/platform aws
Fixes leftover bastion test
https://github.com/gardener/gardener-extension-provider-aws/pull/139#issuecomment-660786186
Relevant prs  #4 #139 
```improvement operator
NONE
```
=> fix bastion infra test

charts/internal/shoot-storageclasses/templates/storageclasses.yaml
Signed-off-by: RyderXia <ryder.xia@sap.com>
/area storage
/platform aws
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/145
```improvement user
create default VolumeSnapshotClass if kubernetes version >= 1.18
```
=> create default VolumeSnapshotClass if kubernetes version >= 1.18

docs/usage-as-end-user.md, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area security
/platform aws
The PR enables encryption by default for EBS volumes used by AWS EC2 instances. 
Fixes #126 
This might cause issues with machines that do not support encryption by default. Refer list here - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#ebs-encryption-requirements. 
However, this is something that can be overridden by setting the encryption flag to `false` on the [machine volume settings here](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L49). 
I checked with our cloud profile and I found 6 machine types with `g4dn` which don't have …
=> Enable encryption by default AWS instance EBS vols

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/platform aws
**What this PR does / why we need it**:  This PR populates the controller-configurations on the machine-deployment from worker-object. It also revendors the MCM 0.33.0. 
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/148
The following dependencies need to be resolved.
```improvement operator
Worker extension allows configuring following parameters on machine-deployment: drainTimeout, creationTimeout, healthTimeout, maxEvictRetries, nodeConditions.
```
=> Configure mcm-settings from worker to machine-deployment.

charts/internal/aws-infra/templates/main.tf
/kind bug
/platform aws
Create gateway endpoints when existing vpc is used as well.
Fixes #156
```improvement operator
Gateway endpoints are now also created when existing vpc (`networks.vpc.id`) is used.
```
=> Create gateway endpoints when existing vpc is used

pkg/aws/client/client.go, pkg/aws/client/types.go, pkg/controller/infrastructure/actuator_reconcile.go
/platform aws
When an existing VPC is used for the shoot infrastructure then we require both `enableDnsSupport` and `enableDnsHostnames` to be set to `true`, see also the user documentation: https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage-as-end-user.md#infrastructureconfig
This was not validated earlier, i.e., when such a VPC was used, the shoot reconciliation often failed because the worker nodes couldn't join the cluster. The end-user did not know why this is the case and required support.
With this PR, we check the VPC attributes upfront before the `Infrastructure` reconciliation to clearly indicate this error.
**Which …
=> Infrastructure controller validates VPC attributes

charts/gardener-extension-validator-aws/charts/runtime/templates/poddisruptionbudget.yaml
/area high-availability robustness
/platform aws
This PR adds a `PodDisruptionBudget` to the validator chart which will be created when the replica count is larger than `1`, similar to how it's done for the extension controller.
/invite @ialidzhikov @timuthy 
```improvement operator
A `PodDisruptionBudget` for the validation server is now automatically deployed as part of its Helm chart if the replica count is larger than `1`.
```
=> Add PDB for validation server

charts/images.yaml
/area storage
/kind task
/platform aws
Update amazon/aws-ebs-csi-driver to v0.6.0.
```improvement user
`amazon/aws-ebs-csi-driver` is now updated to `v0.6.0`.
```
=> Update amazon/aws-ebs-csi-driver to v0.6.0

docs/usage-as-end-user.md, docs/usage-as-operator.md
/platform aws
This PR adds documentation about the required AWS IAM user privileges for both usage as end-user (for shoots) and usage as operator (for backups).
```improvement operator
NONE
```
=> Add docs about required infrastructure user privileges

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
/kind bug
/platform aws
This PR allows the `.networks.zones[].elasticIPAllocationID` field to be changed in the `InfrastructureConfig` as it is supposed to be, see https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage-as-end-user.md#infrastructureconfig.
Thanks @guydaichs for reporting!
```improvement user
A bug has been fixed which prevented the `.networks.zones[].elasticIPAllocationID` field in the `InfrastructureConfig` from being changed.
```
=> Allow elastic IP allocation ID to be changed

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml, docs/usage-as-end-user.md, pkg/aws/types.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/area storage
/kind task
/platform aws
Allow passing --volume-attach-limit to the csi driver. Ref https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/522.
Fixes #159
Depends on:
```improvement operator
`provider-aws` does now allow configuring the `--volume-attach-limit` flag of the AWS EBS CSI driver via `aws.provider.extensions.gardener.cloud/volume-attach-limit` annotation on Shoot.
```
=> Allow passing --volume-attach-limit to the csi driver

Makefile, test/integration/infrastructure/infrastructure_test.go
/platform aws
- Add make target for infra integration test
- Use `aws-infrastructure-it--` as a namespace prefix to avoid confusion
Fixes #
/cc @ialidzhikov 
```improvement operator
NONE
```
=> Add make target for infra integration test

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/area os
/kind bug
/platform aws
Adds a host path volume to the KCM that is required for certain OS.
The KCM discovers the Root CAs available on the node via [predefined locations](https://github.com/golang/go/blob/1bb247a469e306c57a5e0eaba788efb8b3b1acef/src/crypto/x509/root_linux.go#L7-L15).
```
"/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.
"/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL 6
"/etc/ssl/ca-bundle.pem",                            // OpenSUSE
"/etc/pki/tls/cacert.pem",                           // OpenELEC
"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7
"/etc/ssl/cert.pem", …
```
=> Add kcm mounts when not using csi

README.md, charts/images.yaml
/area open-source usability
/platform aws
This PR adds support for 1.19 to the extension.
Part of gardener/gardener#2629
* I have successfully validated the functionality as follows:
* :white_check_mark: Create new clusters with versions < 1.19
* :white_check_mark: Create new clusters with version  = 1.19
* :white_check_mark: Upgrade old clusters from version 1.18 to version 1.19
* :white_check_mark: Delete clusters with versions < 1.19
* :white_check_mark: Delete clusters with version  = 1.19
```noteworthy user
The AWS extension does now support shoot clusters with Kubernetes version 1.19. You …
```
=> Support for Kubernetes 1.19

charts/images.yaml
/kind bug
/priority blocker
/platform aws
The deletion of VMs referring to a non-existing disk image fails currently. This MCM hotfix fixes this issue.
Fixes #
Link to MCM hotfix - https://github.com/gardener/machine-controller-manager/releases/tag/v0.33.1
```noteworthy user
The deletion of VMs referring to a non-existing disk image fails currently. This MCM version hotfix fixes this issue.
```
=> github.com/gardener/machine-controller-manager:v0.33.0->v0.33.1

README.md
/platform aws
Adding known compatibility document.
Fixes #
```noteworthy operator
Adding known compatibility issue for AWS extension `<= v1.15.0`  and Gardenlet `>v1.10.0`. 
Please check the document under /docs/compatibilty. 
```
=> Add compatibility notes

.test-defs/provider-aws-extended.yaml
/platform aws
This PR adds additional test definition "provider-aws-extended" that includes all parameters from the respective test file, not only the mandatory, like the "provider-aws" test definition.
This test definition will be used by the integration tests where shoots with different networks from the defaults must be created (e.g. for registering a new seed for the control plane migration).
Fixes #
NONE
=> Adding additional test definition provider-aws-extended 

.golangci.yaml
/kind cleanup
/platform aws
We added this exclusion back in d804e2b37c1644ef4657bdbd859031b1a09d290b to prevent the following failure:
```
$ make check
> Check
Executing golangci-lint
test/e2e/networkpolicies/networkpolicy_test.go:35:2: SA1019: package github.com/gardener/gardener/test/integration/framework is deprecated: this is the deprecated gardener testframework. Use gardener/test/framework instead  (staticcheck)
gardenerframework "github.com/gardener/gardener/test/integration/framework"
^
make: *** [check] Error 1
```
But in 0a4f1f16d3d380f3fa8123e1b267f50e9ac83b77 `test/e2e/networkpolicies/networkpolicy_test.go` is deleted.
So we can now bring back the check that prevents …
=> Nit: Do no longer ignore deprecated item usage

Dockerfile
/kind impediment
/platform aws
The upstream docker image downloads are running into rate limits. 
Fixes #
```improvement operator
NONE
```
=> Update docker images to use GCR copy for release-v1.16

Dockerfile
/platform aws
Reverts gardener/gardener-extension-provider-aws#224 as needs https://github.com/gardener/gardener/pull/3189 to be able to use the gcr copy images as mentioned by @ialidzhikov. Will wait for the rate limits to stop throlling. 
Fixes #
```improvement operator
NONE
```
=> Revert "Update docker images to use GCR copy for release-v1.16"

charts/images.yaml
from v0.35.1 to v0.35.2
/kind bug
/platform aws
This MCM hotfix handles the issues created by panicking of machineset names shorter than length of 5 
Fixes https://github.com/gardener/machine-controller-manager/issues/500
``` improvement operator github.com/gardener/machine-controller-manager #577 @AxiomSamarth
An issue causing panic when the encoded machine template hash length is less than expect limit is now fixed.
```
=> Bump MCM version from 0.35.1 to 0.35.2

charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser.yaml, charts/internal/machine-controller-manager/seed/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/service.yaml, test/e2e/netpol-gen/app/aws.go, test/e2e/networkpolicies/networkpolicy_test.go
/kind cleanup
/platform aws
Currently the shoot care controller of gardenlet is using the label selector `garden.sapcloud.io/role=controlplane` to health check the required controlplane components. Since longtime machine-controller-manager, cloud-controller-manager and aws-lb-readvertiser are not among the required controlplane deployments. Their health checks are now performed by the extension health check library. So we can now cleanup the `garden.sapcloud.io/role` label key to prevent unnecessary listing and computations from the gardenlet's shoot care controller.
On the other hand we need to keep the `garden.sapcloud.io/role=controlplane` label on the Pods as dependency-watchdog-endpoint component …
=> Remove deprecated role label key from components

charts/images.yaml, pkg/controller/infrastructure/actuator.go
/area quality robustness
/platform aws
This PR let the infrastructure actuator use the terraformer v2.
```noteworthy operator
The terraformer version has been upgraded to version `v2.0.0`.
```
/invite @timebertt
=> Terraformer v2

charts/images.yaml
/area storage
/platform aws
```feature user
The following image is updated:
- k8s.gcr.io/provider-aws/aws-ebs-csi-driver: v0.7.0 -> v0.8.0
aws-ebs-csi-driver@v0.8.0 adds support for EBS gp3 volumes. For more details, see the [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v0.8.0/CHANGELOG-0.x.md#v080).
```
=> Update aws-ebs-csi-driver to v0.8.0

charts/images.yaml, charts/internal/machine-controller-manager/seed/templates/deployment.yaml, charts/internal/machine-controller-manager/seed/values.yaml, charts/internal/machineclass/templates/machineclass.yaml, pkg/aws/types.go, pkg/controller/worker/machine_controller_manager.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
- This also includes migration from AWSMachineClass to MachineClass. This migration occurs implicitly without causing rollouts of existing nodes/VMs.
- Added tests to verify deletion of old machineClass objects
/kind  api-change
/platform aws
Fixes #
```breaking operator
⚠️ Before upgrading your `gardener/gardener-extension-provider-aws` to [>= v1.20.0](https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.20.0), please upgrade your `gardener/gardener` component version to [>= v1.14.0](https://github.com/gardener/gardener/releases/tag/v1.14.0) to avoid breaking of …
```
=> Migration of in-tree to out-of-tree MCM providers

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
/area storage
/kind bug
/platform aws
This PR configures the csi-provisioner and aws-ebs-csi-driver to add in-tree volume plugin tags to volumes to keep the backwards-compatibility. See https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/530
Currently a volume provisioned with the in-tree volume plugin has the following tags:
```
KubernetesCluster                        shoot--foo--bar1     
Name                                     shoot--foo--bar1-dynamic-pvc-a78c281f-78d5-46cd-8849-3fc2bd04ab28     
kubernetes.io/cluster/shoot--foo--bar1   owned     
kubernetes.io/created-for/pv/name        pvc-a78c281f-78d5-46cd-8849-3fc2bd04ab28     
kubernetes.io/created-for/pvc/name       pvc-name
kubernetes.io/created-for/pvc/namespace  default
```
Currently (before this PR) …
=> Add in-tree volume plugin tags to CSI provisioned volumes

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
Cherry pick of #256 on release-v1.19.
#256: Add in-tree volume plugin tags to CSI provisioned volumes
```bugfix user
Volumes provisioned with CSI will now have the in-tree volume plugin tags. Until now the CSI volumes had no tags at all. This is required to keep CSI plugin backwards-compatible with the in-tree volume plugin.
```
=> [release-v1.19] Add in-tree volume plugin tags to CSI provisioned volumes

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go, vendor/modules.txt
/kind bug
```bugfix operator
An issue causing the generic Worker actuator to not wait until the finalizer of the out-of-tree machine controller provider is removed from the credentials secret is now fixed.
```
=> Vendor gardener/gardener@v1.16.1

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go, vendor/modules.txt
/kind bug
Cherry pick of #269 on release-v1.20.
#269: Vendor gardener/gardener@v1.16.1
```bugfix operator
An issue causing the generic Worker actuator to not wait until the finalizer of the out-of-tree machine controller provider is removed from the credentials secret is now fixed.
```
=> [release-v1.20] Vendor gardener/gardener@v1.16.1

charts/gardener-extension-admission-aws/charts/runtime/templates/vpa.yaml, charts/gardener-extension-admission-aws/values.yaml
/area scalability auto-scaling
/platform aws
VPA for validator/admission component
```noteworthy operator
The validator/admission component's Helm chart is now deploying a `VerticalPodAutoscaler` resource by default. If undesired or no VPA is available in the garden cluster then it can be turned of via `.Values.global.vpa.enabled=false`.
```
=> VPA for validator/admission component

.ci/pipeline_definitions
/kind bug
It seems that the publish step is no longer valid after https://github.com/gardener/gardener-extension-provider-aws/pull/281
```other operator
NONE
```
=> Fix the erroneous pipeline definition

pkg/controller/infrastructure/actuator_migrate.go
/platform azure
This PR adds additional cleanup step, that ensures that the terraform finalizers of the terraformer resources are deleted.
Fixes #
Removing the finalizers from the Terraform config resources [#3556](https://github.com/gardener/gardener/pull/3556)
```other operator
NONE
```
=> Ensuring that the terraformer finalizer is removed during cleanup

charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/vpa.yaml
/area auto-scaling
/platform aws
To avoid OOM killing of the AWS cloud controller manager it is needed to activate `minAllowed` settings in its VPA object.
Fixes #
```other operator
The cloud-controller-manager VPA does no specify minAllowed values to prevent too low resource recommendations from VPA that lead to OOM.
```
=> activate minAllowed for cloud-controller-manager VPA

pkg/controller/infrastructure/actuator_delete.go, test/integration/infrastructure/infrastructure_test.go
/area ops-productivity robustness scalability
/priority critical
/platform aws
We are now skipping the explicit LB deletion when the shoot is of at least Kubernetes v1.16
See also: https://github.com/gardener/gardener/issues/129
```other user
The load balancers and security groups are no longer explicitly deleted by the AWS provider extension when a shoot cluster of at least Kubernetes v1.16 is being deleted. Instead, it now relies on the service-controller in the `cloud-controller-manager` to properly clean up.
```
=> Skip explicit LB deletion for Kubernetes >= v1.16

pkg/controller/infrastructure/actuator_delete.go, test/integration/infrastructure/infrastructure_test.go
Cherry-pick of #290.
```other user
The load balancers and security groups are no longer explicitly deleted by the AWS provider extension when a shoot cluster of at least Kubernetes v1.16 is being deleted. Instead, it now relies on the service-controller in the `cloud-controller-manager` to properly clean up.
```
=> [release-v1.20] Skip explicit LB deletion for Kubernetes >= v1.16

charts/images.yaml
/area storage
Fixes #289
```other user
The following image is updated:
- k8s.gcr.io/provider-aws/aws-ebs-csi-driver: v0.8.0 -> v0.9.0 (see [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v090))
```
=> Update aws-ebs-csi-driver to v0.9.0

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
`csi-driver-controller` Deployment is now annotated with the controlplane labels to allow the `dependency-watchdog` to restart the csi-driver-controller when the apiserver recovers.
Ref https://github.com/gardener/gardener/blob/v1.18.0/docs/usage/seed_bootstrapping.md#endpoint
```other operator
NONE
```
=> Add controlplane label to csi-driver-controller

pkg/aws/client/client.go, pkg/aws/client/types.go, pkg/controller/infrastructure/actuator_delete.go, pkg/controller/infrastructure/actuator_reconcile.go, test/integration/infrastructure/infrastructure_test.go
/area scalability robustness ops-productivity
/priority 3
/platform aws
With https://github.com/gardener/gardener-extension-provider-aws/pull/290 we had disabled the explicit deletion for clusters >= 1.16. However, we see some occasional issues with leaked LB/SG, so let's reactivate it again and improve the code to reduce the number of API calls.
/assign @ialidzhikov 
/invite @ialidzhikov 
/squash
Earlier, we listed all LBs and executed a `DescribeTags` call for each load balancer. Now, we first list LB and execute only one `DescribeTags` call with all the found LB names. This should significantly improve the overall number of API calls (especially, when many …
=> Activate explicit LB/SG deletion again and improve code to reduce API calls

charts/images.yaml
/kind bug
This reverts commit c57ddb75ab948788b13474d9c36d3d85137363d8.
The new version of terraformer comes with a new version of terraform-provider-aws - ref https://github.com/gardener/terraformer/pull/84. The new version of terraform-provider-aws requires permissions for `iam:ListRolePolicies` which is currently not part of our officially recommended IAM policy. So it is incompatible change:
```
* reading inline policies for IAM role shoot--foo--bar-nodes, error: AccessDenied: User: technical-user is not authorized to perform: iam:ListRolePolicies on resource: role shoot--foo--bar-nodes
status code: 403, request id: <omitted>
```
```bugfix user
An issue causing Infrastructure reconciliation to fail because of insufficient privileges is now fixed.
```
=> Revert "Upgrade terraformer #294"

charts/images.yaml
/kind bug
Cherry pick of #301 on release-v1.22.
#301: Revert "Upgrade terraformer #294"
```bugfix user
An issue causing Infrastructure reconciliation to fail because of insufficient privileges is now fixed.
```
=> [release-v1.22] Automated cherry pick of #301: Revert "Upgrade terraformer #294"

.test-defs/infrastructure-test.yaml, .test-defs/provider-aws.yaml, Dockerfile
/kind bug
After https://github.com/gardener/gardener-extension-provider-aws/pull/307, the test execution fails with:
```
vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader.go:19:2: cannot find package "." in:
/go/src/github.com/gardener/gardener-extension-provider-aws/vendor/embed
FAIL	github.com/gardener/gardener-extension-provider-aws/test/integration/infrastructure [setup failed]
FAIL
```
The embed pkg is only present in go@1.16, so we should also update the golang version in the TestDefinition.
```other operator
NONE
```
=> Fix the infrastructure-test TestDefinition

pkg/controller/infrastructure/actuator_delete.go, test/integration/infrastructure/infrastructure_test.go
/kind bug
/platform aws
Today, the explicit LB/SG deletion relies on the Terraform output variable for the VPC ID. However, in case an existing VPC is used (`.networks.vpc.id != nil`), during `terraform destroy`, the first successfully deleted resource by Terraform removes this output variable and never puts it back. If the destruction now fails and the deletion flow is re-invocated, the explicit LG/SG deletion is skipped and never executed again.
With this PR, we no longer rely on the Terraform output variable if `.networks.vpc.id != nil`. Hence, the explicit LB/SG deletion will be properly retried for each invocation as long as the Terraform job did not succeed. This helps to destroy LB/SG …
=> Use VPC ID from InfrastructureConfig if possible

docs/usage-as-end-user.md
/platform aws
Part of https://github.com/gardener/gardener-extension-provider-aws/issues/319
```other user
The recommended AWS IAM policy does now contain additional permission (action) `iam:ListRolePolicies`. The addition of the new permission is a preparation for an upcoming breaking change that will require this permission (action) to be present. For more details, see the corresponding announcement [Upcoming change to AWS IAM policy](https://groups.google.com/g/gardener/c/sIwiQp6ak_4/m/y2mUd3_lAAAJ).
```
=> Adapt the IAM policy for terraformer-provider-aws >= 3.29.1

charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
/platform aws
The new rule allows listing and watching of `PodDisruptionBudgets` required by newer versions of MCM
Refer - https://github.com/gardener/machine-controller-manager-provider-aws/pull/23
Fixes #
This is similar to the changes that were made on [other providers](https://github.com/gardener/gardener-extension-provider-openstack/blame/master/charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml#L63-L69)
```other operator
NONE
```
/invite @ialidzhikov
=> Update ClusterRoles for MCM

pkg/controller/bastion/actuator_reconcile.go, test/integration/bastion/bastion_test.go
/kind bug
/platform aws
The testcase wasn't representing what is actually stored in the Bastion. `[]byte` is already stored as base64.
```other operator
NONE
```
=> [GEP-15] fix wrong base64 encoding for bastion instance userdata

charts/images.yaml
Cherry pick of #339 on release-v1.24.
#339: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.6.0->v0.7.0]
**Special notes for reviewer**
This bumps MCM by 2 versions, however, the previous version only contained a minor change and should not affect this. Refer https://github.com/gardener/gardener-extension-provider-aws/pull/331. 
``` other dependency github.com/gardener/machine-controller-manager-provider-aws #35 @prashanth26
Revendors MCM dependent libraries for `v0.39.0` version.
```
=> [release-v1.24] Automated cherry pick of #339: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.5.0->v0.7.0]

charts/images.yaml
Cherry pick of #338 on release-v1.24.
#338: [ci:component:github.com/gardener/machine-controller-manager:v0.38.0->v0.39.0]
``` bugfix developer github.com/gardener/machine-controller-manager #611 @prashanth26
Adds finalizers on machines that are adopted by the machine controller. Without this change, it causes issues while migrating machine objects between clusters.
```
``` bugfix operator github.com/gardener/machine-controller-manager #609 @jsravn
Fix panic when machineClass `secretRef` isn't found.
```
``` feature operator github.com/gardener/machine-controller-manager #607 @himanshu-kun
Improved log details to include node name and provider-ID in addition to existing machine name
```
``` feature user github.com/gardener/machine-controller-manager #605 @himanshu-kun …
```
=> [release-v1.24] Automated cherry pick of #338: [ci:component:github.com/gardener/machine-controller-manager:v0.38.0->v0.39.0]

charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml
/kind bug
Currently admission-aws fails to start with:
```
E0526 11:58:45.881288       1 reflector.go:138] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:137: Failed to watch *v1beta1.SecretBinding: failed to list *v1beta1.SecretBinding: secretbindings.core.gardener.cloud is forbidden: User "system:serviceaccount:garden:gardener-extension-admission-aws" cannot list resource "secretbindings" in API group "core.gardener.cloud" at the cluster scope
```
Follow-up after https://github.com/gardener/gardener-extension-provider-aws/pull/336
```other operator
NONE
```
=> Update the admission-aws RBAC after cloud provider Secrets validation feature

charts/images.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Similar to https://github.com/gardener/gardener-extension-provider-openstack/pull/287 and https://github.com/gardener/gardener-extension-provider-openstack/pull/288.
```other user
The following image is updated (see [CHANGELOG](https://github.com/kubernetes-csi/livenessprobe/blob/v2.3.0/CHANGELOG/CHANGELOG-2.3.md) for more details):
- k8s.gcr.io/sig-storage/livenessprobe: v2.2.0 -> v2.3.0
```
=> Reduce the verbosity of csi-driver-node logs

pkg/apis/aws/validation/secrets.go, pkg/apis/aws/validation/secrets_test.go
/platform aws
Enhances the validation of AWS cloud provider secrets:
* `accessKeyID` must only contain alphanumeric characters, see https://docs.aws.amazon.com/IAM/latest/APIReference/API_AccessKey.html
* `secretAccessKey` must only contain base64 characters, see https://aws.amazon.com/blogs/security/a-safer-way-to-distribute-aws-credentials-to-ec2/
Fixes #
The above AWS security blog is not authoritative documentation. On the other hand, all `secretAccessKeys` we have seen so far do indeed contain only base64 characters. I think the proposed validation will in practice always match valid keys …
=> Enhance validation of cloud provider secrets

go.mod, go.sum, pkg/aws/csimigration.go, pkg/aws/csimigration_test.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/csimigration/add.go, pkg/controller/healthcheck/add.go, pkg/webhook/controlplane/ensurer.go, vendor/github.com/gardener/gardener/charts/images.yaml, vendor/github.com/gardener/gardener/extensions/pkg/controller/csimigration/controller.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/csimigration/reconciler.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/general/managed_resource.go, vendor/github.com/gardener/gardener/extensions/pkg/predicate/predicate.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go, vendor/github.com/gardener/gardener/hack/hook-me.sh, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go, vendor/github.com/gardener/gardener/pkg/apis/core/validation/cloudprofile.go, vendor/github.com/gardener/gardener/pkg/apis/core/validation/shoot.go, vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go, vendor/github.com/gardener/gardener/pkg/extensions/customresources.go, vendor/github.com/gardener/gardener/pkg/operation/common/types.go, vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go, vendor/github.com/gardener/gardener/pkg/utils/kubernetes/kubernetes.go, vendor/github.com/gardener/gardener/pkg/utils/kubernetes/unstructured/object.go, vendor/modules.txt
/area storage
/platform aws
This PR adds support for overwriting the Kubernetes version for which CSI migration shall be performed on `Shoot` level.
⚠️ This feature is to be considered alpha/experimental and usage is on your own risk.
/squash
✅ Depends on gardener/gardener#4202
```other operator
Support for overwriting the CSI migration version was added.
```
=> Enable to overwrite the Kubernetes version for CSI migration on Shoot level

pkg/controller/worker/helper.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area auto-scaling
/platform aws
adds driver specific CSI label `topology.ebs.csi.aws.com/zone` during machineDeployment creation 
Fixes #364 
also made changes to unit test written for machineDeployment generation by adding relevant variables
```other operator
AWS CSI driver specific topology label  "topology.ebs.csi.aws.com/zone" is set as a label on machine deployments to allow the proper working of cluster-autoscaler during scale-up. 
```
=> Setting CSI AWS topology label on machine deployment creation to allow scale-up

pkg/controller/worker/helper.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area/auto-scaling
/kind/enhancement
Cherry pick of #365 on release-v1.25.
#365: Setting CSI AWS topology label on machine deployment creation to allow scale-up
```other operator
AWS CSI driver specific topology label "topology.ebs.csi.aws.com/zone" is set as a label on machine deployments to allow the proper working of cluster-autoscaler during scale-up. 
```
=> [release-v1.25] Automated cherry pick of #365: Setting CSI AWS topology label on machine deployment creation to allow scale-up

charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
/area testing
/area storage
/kind bug
/platform aws
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/70
Currently we observe flakes in the `guestbook app` test that are related to the csi-driver-node component. We see that the corresponding Pod fails to start:
```
time="2021-07-05T10:09:22Z" level=info msg="Pod csi-driver-node-mg8l4 is Pending on Node ip-10-250-10-76.eu-west-1.compute.internal"
```
The reason is 
```
time="2021-07-05T10:09:22Z" level=info msg="At 2021-07-05 09:34:10 +0000 UTC - event for csi-driver-node-mg8l4: {kubelet ip-10-250-10-76.eu-west-1.compute.internal} Failed: Error: Error response from daemon: Minimum memory limit allowed is 6MB"
time="2021-07-05T10:09:22Z" level=info msg="At 2021-07-05 09:34:10 +0000 UTC - event for …
```
=> Set minAllowed memory for csi-driver-node containers

charts/internal/aws-lb-readvertiser/templates/aws-lb-readvertiser-vpa.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
/area/storage
/area/testing
/kind/bug
Cherry pick of #369 on release-v1.25.
#369: Set minAllowed memory for csi-driver-node containers
```other operator
An issue preventing `csi-driver-node` Pod to start because of too low memory recommendation by VPA is now fixed.
```
=> [release-v1.25] Automated cherry pick of #369: Set minAllowed memory for csi-driver-node containers

docs/usage-as-end-user.md
=> Document limitation about encryption with customer managed CMKs

pkg/aws/client/client_route53.go, pkg/controller/dnsrecord/actuator.go, pkg/controller/dnsrecord/actuator_test.go
/platform aws
Categorizes certain aws-route53 errors as configuration problems as suggested in https://github.com/gardener/gardener/issues/4294.
Fixes https://github.com/gardener/gardener/issues/4294
```other operator
Failures to reconcile `DNSRecords` due to a missing hosted zone or a DNS name not matching the zone name are now properly categorized as `ERR_CONFIGURATION_PROBLEM`.
```
=> Categorize certain aws-route53 errors as configuration problems

pkg/controller/worker/machines.go
/platform aws
This PR introduces a new field in the `providerSpec` of `MachineClass` for AWS called `srcAndDstChecksEnabled ` which is `true` by default and when set to `false` will disable the source destination check on the AWS Instance (NAT instance in this case). This field shall be used by default from K8s >= v1.22
Fixes [#36](https://github.com/gardener/machine-controller-manager-provider-aws/issues/36)
```feature developer
Introducing a new field in the `providerSpec` of `MachineClass` for AWS called `srcAndDstChecksEnabled ` which is `true` by default and when set to `false` will disable …
```
=> Enable `srcAndDstChecksEnabled` field from k8s >= v1.22

go.mod, pkg/apis/aws/helper/scheme.go, pkg/aws/client/client.go, pkg/controller/bastion/actuator.go, pkg/controller/bastion/actuator_delete.go, pkg/controller/bastion/actuator_reconcile.go, pkg/controller/bastion/options.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/worker/helper.go, pkg/controller/worker/machine_images.go, pkg/controller/worker/machines.go, pkg/webhook/shoot/mutator.go, test/tm/generator.go, vendor/modules.txt
/kind cleanup
/platform aws
Similar to gardener/gardener#4280 we should be using Go native error wrapping (available since GO 1.13).
Fixes #375
```NONE
```
/invite @vanjiii
=> Stop using `github.com/pkg/errors`

.landscaper/blueprint/blueprint.yaml, .landscaper/blueprint/deploy-execution-manifests.yaml
/area delivery
/platform aws
This pull request fixes and updates the blueprint of the provider-aws component.
The blueprint contains data, which in the current deployment are in the templates for the [cloud profile](https://github.wdf.sap.corp/kubernetes/landscape-setup/blob/master/components/gardener-extensions/provider-aws/resources/10-cloudprofile.yaml.tpl) and [controller deployment / registration](https://github.wdf.sap.corp/kubernetes/landscape-setup/blob/master/components/gardener-extensions/provider-aws/resources/controllerregistration.yaml.tpl). We have updated the blueprint so that it contains the last changes from there. 
We plan to activate the landscaper based deployment for provider-aws …
=> Update blueprint for component provider-aws 

charts/images.yaml
/area/storage
/kind/bug
Cherry pick of #411 on release-v1.28.
#411: Update aws-ebs-csi-driver
```other user
The following image is updated:
- k8s.gcr.io/provider-aws/aws-ebs-csi-driver: v1.1.1 -> v1.1.4 (see [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-1.1/CHANGELOG-0.x.md#v114))
```
=> [release-v1.28] Automated cherry pick of #411: Update aws-ebs-csi-driver

.golangci.yaml, pkg/admission/validator/webhook.go, pkg/apis/config/loader/loader.go, pkg/aws/client/client.go, pkg/aws/matchers/iam_role_policy_document.go, pkg/controller/dnsrecord/actuator.go, test/integration/vpc.go, test/tm/generator.go
/area quality, dev-productivity
/platform aws
Makes the linter fail on missing or wrong doc comments and a few other common style errors, and fixes all such issues that already exist.
Fixes #
Making the linter fail on missing or wrong doc comments and a few other common style errors consists of enabling `revive` in the `golangci-lint` configuration and excluding certain `revive` errors that we are perhaps not interested in.
I have fixed the following `revive` errors (as regexes that could be included in the `golangci-lint` configuration if desired):
```
- "exported: comment on exported (var|const|type|method|function) .* should be …
```
=> Make the linter fail on missing or wrong doc comments

charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
/area/robustness
/area/storage
/kind/enhancement
Cherry pick of #421 on release-v1.29.
#421: Increase cpu resources for csi-driver
```other operator
The CPU limit of `csi-driver-node/csi-driver` is increased from 50m to 100m to allow bigger bursts.
```
=> [release-v1.29] Automated cherry pick of #421: Increase cpu resources for csi-driver

pkg/aws/client/client.go, pkg/aws/client/mock/mocks.go, pkg/aws/client/types.go, pkg/controller/infrastructure/configvalidator.go, pkg/controller/infrastructure/configvalidator_test.go
/area quality
/platform aws
- checks if the specified EIPs exist
- checks if the EIP is already associated to another AWS resource and thus cannot be associated with the NAT Gateway of the Cluster
Fixes #429
I tried to test all scenarios locally (with / without EIP, reconcile, add invalid EIP, update EIP).
```other operator
Specified Elastic IP addresses are now validated: must exist & must not be already associated with another AWS resource.
```
=> Add validation for non-existing and already wrongly-associated EIPs

README.md
/kind/enhancement
/area/testing
Cherry pick of #440 on release-v1.30.
#440: Add Kubernetes v1.22 conformance badge
```doc developer
Kubernetes v1.22 conformance badge is now added to the README.md.
```
=> [release-v1.30] Automated cherry pick of #440: Add Kubernetes v1.22 conformance badge

charts/gardener-extension-admission-aws/charts/application/templates/validatingwebhook-validator.yaml, charts/gardener-extension-admission-aws/charts/runtime/templates/secret-cert.yaml
/area quality
/kind bug
/platform aws
Previously when trying to install the admission helm chart without providing `.global.webhookConfig.caBundle` (for example) the helm deployment was failing with an error similar to this one:
```
... at <.Values.global.webhookConfig.caBundle>: wrong type for value; expected string; got interface {}
```
After the change the same installation will fail with a message that is actually desired.
```
... execution error at (gardener-extension-admission-aws/charts/application/templates/validatingwebhook-validator.yaml:35:17): .Values.global.webhookConfig.caBundle is required
```
Fixes #
```other …
```
=> Improve the error message when a required part of webhookConfig is missing

charts/images.yaml
**Release Notes**:
``` other operator github.com/gardener/terraformer #110 @ialidzhikov
The following terraform provider plugins are updated:
- hashicorp/terraform-provider-aws: 3.63.0 -> 3.66.0
```
=> [ci:component:github.com/gardener/terraformer:v2.12.0->v2.12.1]

charts/internal/machineclass/Chart.yaml, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/kind cleanup
/platform aws
Removes AWSMachineClass cleanup
Fixes #
```breaking operator
Removes the cleanup for the older AWSMachineclasses during worker reconciliation.
```
=> Remove awsmachineclass cleanup

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
/area quality
/platform aws
Similar to https://github.com/gardener/gardener-extension-provider-alicloud/pull/400
```other operator
NONE
```
=> Prevent nil pointer dereference in admission-aws

charts/images.yaml, pkg/aws/client/client.go, test/integration/dnsrecord/dnsrecord_test.go
/platform aws
Upgrades `terraformer` image to v2.13.0, a version that uses `terraform` 0.13.
Fixes #
**Release Notes**:
``` other operator github.com/gardener/terraformer #105 @stoyanr
terraform has been upgraded to 0.13.7
```
=> Upgrade terraformer to v2.13.0, a version that uses terraform 0.13

pkg/controller/infrastructure/templates/main.tpl.tf
/area quality
/kind bug
/platform aws
For accounts that host large amount of Shoots the default aws_route_table creation timeout (`2m`) can be not enough in some cases. In such AWS accounts we see that the route table creation cannot complete for `2m` and this leads to consistency issues (the concrete upstream issue is https://github.com/hashicorp/terraform-provider-aws/issues/21829).
In terraform-provider-aws > 3.70.0 to mitigate/fix this consistency issue the default aws_route_table creation timeout was increased to `5m` (as done in this PR).
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency also mentions that the wait time should be up to 5m.
```bugfix operator
The creation timeouts of `aws_route_table`s are now …
```
=> Increase aws_route_table creation timeout from 2m to 5m

pkg/controller/infrastructure/templates/main.tpl.tf
/area/quality
/kind/bug
Cherry pick of #473 on release-v1.32.
#473: Increase aws_route_table creation timeout from 2m to 5m
```bugfix operator
The creation timeouts of `aws_route_table`s are now increased from `2m` to `5m`.
```
=> [release-v1.32] Automated cherry pick of #473: Increase aws_route_table creation timeout from 2m to 5m

charts/images.yaml
/platform aws
I tested ews-ebs-cs-driver `v1.5.0` with:
1. Dynamic Provisioning
2. CSI Migration
3. Volume Snapshot
4. Volume Resizing
5. Raw block volume
and did not encounter any error.
```other operator
The following image is updated:
- k8s.gcr.io/provider-aws/aws-ebs-csi-driver: v1.1.4 -> v1.5.0 (see [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/release-1.5/CHANGELOG-0.x.md))
```
=> Update aws-ebs-csi-driver to `v1.5.0`

test/integration/infrastructure/infrastructure_test.go
/area testing
/platform aws
```
• Failure [40.112 seconds]
Infrastructure tests
/go/src/github.com/gardener/gardener-extension-provider-aws/test/integration/infrastructure/infrastructure_test.go:95
with invalid credentials
/go/src/github.com/gardener/gardener-extension-provider-aws/test/integration/infrastructure/infrastructure_test.go:253
should fail creation but succeed deletion [It]
/go/src/github.com/gardener/gardener-extension-provider-aws/test/integration/infrastructure/infrastructure_test.go:254
Expected
<[]v1beta1.ErrorCode | len:2, cap:2>: [
"ERR_INFRA_INSUFFICIENT_PRIVILEGES",
"ERR_INFRA_UNAUTHORIZED",
]
to consist of
<[]v1beta1.ErrorCode | len:1, cap:1>: [
"ERR_INFRA_UNAUTHORIZED",
]
the extra elements were
<[]v1beta1.ErrorCode | len:1, cap:1>: [ …
```
=> Fix the infrastructure integration test

pkg/controller/bastion/actuator_delete.go
/area quality
/kind bug
/platform aws
This PR fixes an issue / edge case where the bastion instance is not considered terminated when it is already cleaned up. This causes the bastion resource to never be cleaned up and must be cleaned up by hand:
- delete the [bastion security group](https://github.com/gardener/gardener-extension-provider-aws/blob/be02e4cfa70af128a225491e0aed3458e75c99c9/pkg/controller/bastion/actuator_delete.go#L162-L183)
- remove the finalizer on the bastion extension resource on the seed
- confirm that also the bastion resource on the garden cluster is removed
Alternatively, run the `gardener-extension-provider-aws` that includes this fix which will then proceed with the cleanup.
**Which issue(s) …
=> Fix instance terminated check

example/20-crd-extensions.gardener.cloud_bastions.yaml, go.mod, go.sum, pkg/controller/bastion/actuator_reconcile.go, test/integration/bastion/bastion_test.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go, vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go, vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_bastion.go, vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/crds/templates/crd-bastion.tpl.yaml, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go, vendor/modules.txt
/kind bug
/platform aws
Compared to `gardener/gardener@v1.39.0`, `gardener/gardener@v1.39.4` contains the following fixes that are related to the extension library:
- https://github.com/gardener/gardener/pull/5339
- https://github.com/gardener/gardener/pull/5408
- https://github.com/gardener/gardener/pull/5417
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/482
```bugfix operator
The following dependency is updated:
- github.com/gardener/gardener: v1.39.0 -> v1.39.4
```
=> Vendor gardener/gardener@v1.39.4

charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml, charts/gardener-extension-admission-aws/charts/application/templates/serviceaccount.yaml, charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml, charts/gardener-extension-admission-aws/charts/runtime/templates/serviceaccount.yaml, charts/gardener-extension-admission-aws/values.yaml, docs/deployment.md
/area security
/platform aws
This PR adds: 
- The ability to configure the admission deployment to use service account token volume projection ([ref](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection)).
- The ability to configure a user instead of a service account subject in the `clusterrolebinding` definition when using a "virtual garden" setup. This will enable other possibilities for authentication to the virtual garden, i.e., leveraging [oidc-webhook-authenticator](https://github.com/gardener/oidc-webhook-authenticator).
Fixes #
This PR is related to …
=> Add support for sa token volume projection in admission charts

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
/kind api-change
/platform aws
Currently the extension allows defining gateway endpoints as single identifiers suffixes only, e..g `com.amazonaws.eu-central-1.s3`, although AWS allows the gateway endpoint suffix to be a general subdomain.
This change allows defining VPC Gateway Endpoint for general subdomains, e.g. CodeArtifact endpoints like
`com.amazonaws.eu-central-1.codeartifact.api`.
Fixes #
```feature user
Allow defining VPC Gateway Endpoints for subdomains with dots, e.g. com.amazonaws.eu-central-1.codeartifact.api
```
=> allow gateway endpoints for domain names

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go, vendor/modules.txt
/kind bug
/platform aws
Compared to `gardener/gardener@v1.40.0`, `gardener/gardener@v1.40.1` contains the following fix that is related to the extension library:
- https://github.com/gardener/gardener/pull/5454
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/493
```other operator
NONE
```
=> Vendor gardener/gardener@v1.40.1

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go, vendor/modules.txt
/kind bug
/platform aws
Compared to `gardener/gardener@v1.39.4`, `gardener/gardener@v1.39.5` contains the following fixes that are related to the extension library:
- https://github.com/gardener/gardener/pull/5455
Ref https://github.com/gardener/gardener-extension-provider-aws/issues/482
```bugfix operator
The following dependency is updated:
- github.com/gardener/gardener: v1.39.4 -> v1.39.5
```
=> [release-v1.33] Vendor gardener/gardener@v1.39.5

charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
/kind bug
/platform aws
This PR explicitly sets the `default` serviceaccount to the `admission` deployment when its own serviceaccount is not required.
Fixes a bug which occurs when the `admission` component is deployed with a serviceaccount and then upgraded with `helm upgrade` and `values.yaml` that do not require the serviceaccount anymore. What happens is that the serviceaccount is deleted and `helm` patches the deployment by sending `serviceAccountName: nil`, but there is a duplicate field named `serviceAccount` (deprecated by k8s) which holds the old `serviceAccountName` value and Kubernetes defaults `serviceAccountName` to it. This prevents the upgrade because the said serviceaccount does …
=> Fix serviceaccount defaulting during helm upgrade

charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json, charts/internal/seed-controlplane/charts/cloud-controller-manager/ccm-dashboard.json, charts/internal/seed-controlplane/charts/csi-driver-controller/csi-driver-controller-dashboard.json
/area monitoring
/platform aws
/squash
Similar to https://github.com/gardener/gardener/pull/4229 that adapted g/g dashboards to:
- use UTC by default
- do not longer auto refresh by default
```other operator
The monitoring dashboards provided by this extension:
- are now using UTC by default (instead of the browser time)
- do no longer auto refresh by default
```
=> Improve grafana dashboards

cmd/gardener-extension-provider-aws/app/app.go, pkg/controller/infrastructure/actuator.go, pkg/controller/infrastructure/actuator_delete.go, pkg/controller/infrastructure/actuator_migrate.go, pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/infrastructure/actuator_restore.go, pkg/controller/infrastructure/add.go
/area security
This PR enables projected token mounts for the `terraformer` pods.
Part of gardener/gardener#4659
Part of gardener/gardener#4878
```other operator
The `terraformer` pod deployed as part of shoot control planes is now using auto-rotated `ServiceAccount` tokens when communicating with the seed cluster.
```
=> Use projected token mount for terraformer

charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml
/area security
/kind bug
/platform aws
This PR fixes an issue with the CSI-Driver-Controller `DaemonSet` when `shoot.kubernetes.allowPrivilegedContainers: false` is set:
```
Error creating: pods "csi-driver-node-" is forbidden: unable to validate against any pod security policy: [spec.volumes[4]: Invalid value: "projected": projected volumes are not allowed to be used spec.
```
/cc @rfranzke
```other operator
An issue has been fixed with the `csi-driver-node` PodSecurityPolicy which blocked the creation of new CSI-Driver pods because `projected` volumes are not permitted.
```
=> Allow projected volumes in PSP

charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml
/area/security
/kind/bug
Cherry pick of #510 on release-v1.34.
#510: Allow projected volumes in PSP
```other operator
An issue has been fixed with the `csi-driver-node` PodSecurityPolicy which blocked the creation of new CSI-Driver pods because `projected` volumes are not permitted.
```
=> [release-v1.34] Automated cherry pick of #510: Allow projected volumes in PSP

charts/gardener-extension-admission-aws/charts/application/templates/validatingwebhook-validator.yaml, charts/gardener-extension-admission-aws/values.yaml, example/40-validatingwebhookconfiguration.yaml
/platform aws
This PR adds an object selector for provider type label in the `gardener-extension-admission-aws` webhook. This helps in filtering out only resources having provider type `aws` for validation,
Fixes part of gardener/gardener#4932
Related to gardener/gardener#5472
```other operator
The `gardener-extension-admission-aws` webhook now contains an object selector for provider type label. Please make sure you are running `gardener@v1.42` or later before enabling this.
```
=> Add object selector for provider type in the `gardener-extension-admission-aws` webhook

charts/images.yaml
/kind/bug
Cherry pick of #512 on release-v1.34.
#512: [ci:component:github.com/gardener/machine-controller-manager:v0.43.0->v0.43.1]
``` bugfix user github.com/gardener/machine-controller-manager #687 @himanshu-kun
typo stopping scaleDown disabling during cluster rollout is fixed
```
=> [release-v1.34] Automated cherry pick of #512: [ci:component:github.com/gardener/machine-controller-manager:v0.43.0->v0.43.1]

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/area/usability
/kind/bug
Cherry pick of #515 on release-v1.34.
#515: Keep kubelet's `--cloud-provider` flag even for 1.23+
```bugfix user
An issue preventing load balancers from being functional for K8s 1.23 clusters has been fixed.
```
=> [release-v1.34] Automated cherry pick of #515: Keep kubelet's `--cloud-provider` flag even for 1.23+

charts/images.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-deployment.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-networkpolicy.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-service.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-vpa.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/csi-snaphot-validation-webhook.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml, pkg/aws/types.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/controller/healthcheck/add.go
/platform aws
This PR adds the webhook to provide additional validation to volume snapshot objects i.e. `VolumeSnapshot` and `VolumeSnapshotContent`.
Fixes #489
```feature user
The provider-aws extension now installs the external-snapshotter's validating webhook server for VolumeSnapshot and VolumeSnapshotContent objects. For more details check the corresponding [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1900-volume-snapshot-validation-webhook#kep-1900-add-additional-validation-to-volume-snapshot-objects).
```
=> Add snaphot validation webhook

.dockerignore, Makefile, cmd/gardener-extension-admission-aws/app/app.go, cmd/gardener-extension-provider-aws/app/app.go, vendor/k8s.io/component-base/version/verflag/verflag.go, vendor/modules.txt
/platform aws
For the motivation about this change, see https://github.com/gardener/gardener/issues/2703.
Part of https://github.com/gardener/gardener/issues/2703
This change does not support an effective version handling (https://github.com/gardener/gardener/pull/2500), hence `--version` flag on a released docker image won't return the correct version. For example:
```
$ docker run eu.gcr.io/gardener-project/gardener/extensions/provider-alicloud:v1.34.0 --version=raw
version.Info{Major:"1", Minor:"34+", GitVersion:"v1.34.0-dev", GitCommit:"11c81b369b88958e5a37aae7f52e1d6dc421f8b0", GitTreeState:"clean", BuildDate:"2022-03-17T05:24:24+00:00", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
Note that the version is …
=> Add --version flag for components

pkg/controller/controlplane/valuesprovider.go
/area quality
/kind bug
/platform aws
@Diaphteiros reported that ControlPlane exposure fails to be created/deleted with error:
```yaml
lastError:
description: 'Error deleting controlplane: could not delete control plane exposure
shoot access secret ''shoot-access-aws-lb-readvertiser'' for controlplane ''shoot--foo--aws/aws-exposure'':
an empty namespace may not be set when a resource name is provided'
lastUpdateTime: "2022-04-13T11:08:25Z"
```
We then found out that this issue is fixed in the master branch with a change in https://github.com/gardener/gardener-extension-provider-aws/pull/528.
I am opening this backport/cherry-pick to prevent others hitting this issue.
```bugfix operator
An issue preventing ControlPlane exposure to be successfully reconciled is now fixed. …
```
=> [release-v1.34] Fix ControlPlane exposure reconciliation

charts/images.yaml
/platform aws
With the old registry, the image cannot be pulled:
```
Warning  Failed     13m (x2 over 14m)     kubelet            Failed to pull image "k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.3": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.3": failed to resolve reference "k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.3": k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.5.3: not found
```
Ref https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1213
```other operator
NONE
```
=> Update `aws-ebs-csi-driver` image registry

pkg/admission/validator/shoot.go, pkg/admission/validator/shoot_test.go, pkg/admission/validator/validator_suite_test.go, pkg/apis/aws/validation/secrets_test.go
/kind bug
/platform aws
Fixes #500
```bugfix operator
An issue causing admission-aws to fail a Shoot creation request with `.spec.provider.infrastructureConfig=nil` with 500 Internal server error is now fixed. admission-aws now properly indicates in the response that the corresponding field is required.
```
=> admission-aws: Prevent nil pointer dereference when `.spec.provider.infrastructureConfig` is nil

docs/usage-as-end-user.md, pkg/apis/aws/types_worker.go, pkg/apis/aws/validation/worker.go, pkg/apis/aws/validation/worker_test.go
/area storage
/kind bug
/platform aws
This PR allows setting IOPS for any volume type and moves the validation to the AWS side. 
Fixes #488 
This PR will allow setting IOPS for any valid volume type. The validation of the volume type against the cloud profile is not done here, so I have removed the default case and the test case where it checks setting IOPS for an invalid volume type. Testing on the dev landscape is also done. 
```bugfix user
Users can now set IOPS for a GP3 volume type. Validation of IOPS (i.e. whether it is allowed and is in the specified range for a volume type) is done on the AWS side, so feedback will arrive …
```
=> Allowing IOPS for all volume types, removing IOPS range validation

charts/images.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
/area storage
/platform aws
Fixes #
```other user
The following images are updated:
- k8s.gcr.io/sig-storage/csi-provisioner: v2.1.2 -> v2.2.2 (for kubernetes < 1.20)
- k8s.gcr.io/sig-storage/csi-provisioner: v2.1.2 -> v3.2.0 (for kubernetes >= 1.20)
- k8s.gcr.io/sig-storage/csi-attacher: v3.3.0 -> v3.4.0
- k8s.gcr.io/sig-storage/csi-resizer: v0.5.0 -> v1.5.0
- k8s.gcr.io/sig-storage/csi-snapshotter: v3.0.3 -> v4.2.1 (for kubernetes >= 1.20)
- k8s.gcr.io/sig-storage/snapshot-validation-webhook: v3.0.3 -> v4.2.1 (for kubernetes >= 1.20)
- k8s.gcr.io/sig-storage/snapshot-controller: v3.0.3 -> v4.2.1 (for kubernetes …
```
=> Update various kubernetes-csi images

charts/internal/shoot-storageclasses/templates/storageclasses.yaml
/area storage
/platform aws
Removing the gp2 StorageClass for AWS
@dguendisch @hendrikKahl @BeckerMax 
```other user
Removing the gp2 StorageClass for AWS
```
=> Remove AWS gp2 StorageClass

charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-driver.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml, example/10-fake-shoot-controlplane.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/platform aws
`PodSecurityPolicy` is deprecated and will be disabled in kubernetes v1.25+.
End-users are provided an option to migrate their PSPs before upgrading and disable the `PodSecurityPolicy` admission plugin in the ShootSpec. 
In that case, we should stop deploying our PSPs as well.
- This PR stops deploying PSPs related to `provider-aws` if the plugin is disabled in the Shoot.
Part of https://github.com/gardener/gardener/issues/5250
```breaking operator
Please make sure you're running gardener@v1.52 or above before upgrading to this version.
```
=> Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled 

pkg/controller/healthcheck/add.go
/platform aws
This PR adds QPS and Burst to the config passed to HealthCheck client.
The values used here are from https://github.com/gardener/gardener-extension-provider-aws/blob/003f0af55a373705075c2f361cbd5a74cceef397/example/00-componentconfig.yaml#L7-L8.
This is to prevent client-side throttling issues during health check execution. 
Part of https://github.com/gardener/gardener/issues/6045
/cc @oliver-goetz @timuthy 
```other operator
`QPS` and `Burst` are set in the HealthCheckConfig passed to the Controller.
```
=> Add `QPS` and `Burst` to HealthCheckConfig

charts/internal/machineclass/values.yaml, docs/usage-as-end-user.md, hack/api-reference/api.md, pkg/apis/aws/types_worker.go, pkg/apis/aws/v1alpha1/types_worker.go, pkg/apis/aws/v1alpha1/zz_generated.conversion.go, pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go, pkg/apis/aws/validation/worker.go, pkg/apis/aws/validation/worker_test.go, pkg/apis/aws/zz_generated.deepcopy.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area storage
/platform aws
This PR allows configuring `throughput` for `gp3` volume types in the shoot yaml. The validation of throughput against different volume types is done on the provider side, so the error will be returned after the machine creation step.
Fixes #584 
The following tests were performed on a local gardener setup (Current range of throughput is `125MiB/s - 1000MiB/s`)
(The throughput field is configured in the shoot yaml as part of the `providerConfig`) 
(mcm was run locally for these tests along with the necessary changes done on mcm-provider-aws as per …
=> Adding throughput field in worker config

pkg/webhook/controlplane/add.go, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/platform aws
Enable custom aws route controller per default for kubernetes >= 1.22 unless explicitly disabled.
None.
Requires https://github.com/gardener/gardener-extension-provider-aws/pull/591 as prerequisite.
```other operator
Enable custom aws route controller per default for kubernetes >= 1.22 unless explicitly disabled.
```
=> Enable custom aws route controller per default for kubernetes >= 1.22 unless explicitly disabled.

charts/internal/machine-controller-manager/seed/templates/vpa.yaml, charts/internal/machine-controller-manager/seed/values.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/vpa.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
/area auto-scaling
/platform aws
Limits the range of maximum allowed resource requests to ensure that pods are schedulable
Fixes #
```other operator
NONE
```
=> Adds MaxAllowed for VPA objects

charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
/platform aws
Remove the memory limits of the aws cloud-controller-manager as we saw rare cases were the limits are not sufficient during startup phase.
Fixes #
```other operator
The memory limits of the aws cloud-controller-manager has been removed.
```
=> Drop ccm memory limits

charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
/area quality
/kind bug
/platform aws
Deduplicate livenessProble for admission-aws deployment. Also fix the path to the metrics port value.
Fixes #
```other operator
```
=> Deduplicate livenessProble for admission-aws deployment

charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/deployment.yaml
/kind bug
/platform aws
Fixed wrong placement of the deployment strategy in the deployment spec.
```other operator
NONE
```
=> Fix deployment strategy of aws-custom-route-controller

README.md, charts/images.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, docs/usage-as-end-user.md, docs/usage-as-operator.md, example/10-fake-shoot-controlplane.yaml, example/30-controlplane.yaml, example/30-controlplaneexposure.yaml, example/30-worker.yaml, hack/api-reference/api.json, hack/api-reference/config.json, pkg/controller/controlplane/valuesprovider_test.go, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind cleanup
/platform aws
Part of https://github.com/gardener/gardener-extension-provider-aws/issues/595
```breaking operator
provider-aws no longer supports Shoots with Кubernetes version < 1.17.
```
=> Removes support for kubernetes < 1.17 for AWS extension provider

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind bug
/platform aws
Enable custom aws route controller manager if no provider config is specified.
The custom aws route controller manager is essential to the shoot cluster working without overlay network. Therefore, it needs to be enabled regardless if there is a provider configuration or not. Otherwise, shoot clusters will get no overlay, but no pod routes.
None.
```other operator
Correctly enable aws custom route controller if required to ensure overlay free cluster operation.
```
=> Enable custom aws route controller manager if no provider config is specified.

pkg/controller/infrastructure/templates/main.tpl.tf, test/integration/infrastructure/infrastructure_test.go
/platform aws
The traffic to/from VPC endpoints like S3 is now routed internally by adding route table associations for them.
Fixes #607
```other operator
Add route table associations for VPC endpoints
```
=> Add route table associations for VPC endpoints

charts/internal/seed-controlplane/values.yaml, pkg/controller/controlplane/valuesprovider.go
/kind bug
/platform aws
If a shoot is created with `aws-custom-route-controller` enabled and the controller is disabled later by setting `cloudControllerManager.useCustomRouteController=false` in the `ControlPlaneConfig`, the deployment is not removed.
The control plane deployment cannot deal with such cases. Looks like a minor edge case to me, therefore the fix just scales down the deployment.
Additionally a non-relevant typo was fixed in `charts/internal/seed-controlplane/values.yaml` 
```other operator
NONE
```
=> Scale down if custom-route-controller is disabled after creation

.golangci.yaml, .test-defs/bastion-test.yaml, .test-defs/dnsrecord-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-aws.yaml, Dockerfile, Makefile, pkg/controller/infrastructure/configvalidator.go
- update golang for builder image: `1.18.3` -> `1.19.2`
- update golangci_lint:  `1.45.2` -> `1.49` to prepare switching to golang 1.19 for verify step
```other operator
Update golang for builder image: `1.18.3` -> `1.19.2`
```
=> Update golang for builder image and linter to 1.19 

pkg/controller/infrastructure/templates/main.tpl.tf
/kind impediment
/platform aws
In some account on hyperscaler, the administrator sets up security rule using permission boundary which is bound to iam role and it's not allowed to change by account owner. so we need to ignore this property which is not managed by extension. 
Fixes #
```other operator
```
=> to ignore permission boundary property because it's managed by hyperscaler admin

pkg/controller/infrastructure/templates/main.tpl.tf
/kind impediment
/platform aws
In some account on hyperscaler, the administrator sets up security rule using permission boundary which is bound to iam role and it's not allowed to change by account owner. so we need to ignore this property which is not managed by extension. 
Fixes #
```other operator
```
=> to ignore permission boundary property because it's managed by hyperscaler admin 

README.md, docs/usage-as-end-user.md, example/30-controlplane.yaml, example/30-controlplaneexposure.yaml, example/30-dnsrecord.yaml, example/30-infrastructure.yaml, example/30-worker.yaml
/platform aws
Updates Gardener API Core version in examples and markdowns to `core.gardener.cloud/v1beta1`
Fixes #
```other operator
NONE
```
=> Update API Core version in examples to core.gardener.cloud/v1beta1

charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/deployment.yaml, charts/internal/seed-controlplane/charts/aws-custom-route-controller/values.yaml
/kind bug
/platform aws
Fixes an issue with CRC's kubeconfig secret having incorrect name.
Fixes #
```other operator
```
=> fix crc deployment

charts/gardener-extension-admission-aws/charts/application/templates/mutatingwebhook-mutator.yaml, charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml, example/50-mutatingwebhookconfiguration.yaml
/area quality
/kind bug
/platform aws
After https://github.com/gardener/gardener-extension-provider-aws/pull/635 CREATE/UPDATE requests for Shoots from the core.gardener.cloud/v1alpha1 API fail with:
```
$ k create -f ~/foo.yaml
Error from server: error when creating "foo.yaml": admission webhook "mutation.aws.provider.extensions.gardener.cloud" denied the request: unexpected request kind core.gardener.cloud/v1alpha1, Kind=Shoot
```
This PR removes the v1alpha1 from the mutatingwebhook spec and relies on the `matchPolicy: Equivalent` field of the webhook that will take care to convert the v1alpha1 obj to v1beta1. Ref https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controller …
=> Do not fail a request for a Shoot from the core.gardener.cloud/v1alpha1 API

charts/gardener-extension-admission-aws/charts/application/templates/mutatingwebhook-mutator.yaml, charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml, example/50-mutatingwebhookconfiguration.yaml
/area/quality
/kind/bug
/kind/regression
Cherry pick of #657 on release-v1.40.
#657: Do not fail a request for a Shoot from the core.gardener.cloud/v1alpha1 API
```bugfix operator
An issue causing admission-aws to fail CREATE/UPDATE requests for Shoots from the `core.gardener.cloud/v1alpha1` API is now fixed.
```
=> [release-v1.40] Automated cherry pick of #657: Do not fail a request for a Shoot from the core.gardener.cloud/v1alpha1 API

pkg/apis/aws/helper/helper.go, pkg/apis/aws/helper/helper_test.go
/kind bug
/platform aws
If a cluster gets stuck in the deletion before the upgradation of provider-aws extension version to a version that defaults the machineimage architecture field to amd64 in worker status and if it uses a machine image that is removed from the cloud profile also then shoot deletion will complain that it can't delete shoot cause machine image is found neither in worker status nor in cloud profile of architecture amd64.
This PR enhances the FindMachineImage in such a way that if the machine image doesn't have an architecture field then it is set to amd64.
Fixes #
Similar to …
=> If machine image architecture is nil consider its architecture amd64

pkg/apis/aws/helper/helper.go, pkg/apis/aws/helper/helper_test.go
/kind bug
Cherry pick of #660 on release-v1.40.
#660: If machine image architecture is nil consider its architecture amd64
```other operator
NONE
```
=> [release-v1.40] Automated cherry pick of #660: If machine image architecture is nil consider its architecture amd64

pkg/admission/mutator/mutator_suite_test.go, pkg/admission/mutator/shoot.go, pkg/admission/mutator/shoot_test.go
/kind bug
/platform aws
Mutating webhook respects shoot deletion, restore and migration.Before those operations failed under certain conditions. E.g.: 
```
task "Waiting until shoot infrastructure has been reconciled" failed: shoots.core.gardener.cloud "tmn33-zb3-hs-mgr" is forbidden: cannot change shoot spec during Restore operation that is in state Processing
```
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/659
```other operator
Mutating webhook respects shoot deletion, restore and migration. Before those operations failed under certain conditions.
```
=> Automated cherry pick of #661 upstream release v1.40

go.mod, go.sum, vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/types_network.go, vendor/modules.txt
/kind bug
/platform aws
Update calico version to `v1.27.1`.
This is required because in previous calico versions the `backend` field was not omitted when set to `nil`.
This update will avoid setting `backend: null` in the shoot spec when the shoot mutator webhook in the infrastructure extension is called which leads to an error during validation.
```
error: error validating "STDIN": error validating data: unknown object type "nil" in Shoot.spec.networking.providerConfig.backend; if you choose to ignore these errors, turn validation off with --validate=false
```
Fixes #
```other operator
Update calico version to …
```
=> Update calico version to v1.27.1

pkg/controller/healthcheck/add.go
/platform aws
Add health check for aws-custom-route-controller deployment
Fixes #618 
```other operator
Add health check for aws-custom-route-controller deployment
```
=> Add health check for aws-custom-route-controller deployment

pkg/aws/client/client.go, pkg/aws/client/mock/mocks.go, pkg/aws/client/types.go, pkg/controller/infrastructure/configvalidator.go, pkg/controller/infrastructure/configvalidator_test.go
/area quality
/kind bug
/platform aws
This PR adds validation for `domain-name` of custom dhcp options used in VPCs.
Fixes #615
```bugfix operator
Added validation for `domain-name` of custom dhcp options used in VPCs
```
=> Add validation for `domain-name` of custom dhcp options used in VPCs.

.golangci.yaml, charts/charts.go, pkg/apis/config/loader/loader.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/platform aws
Reintroduce deprecated linting check and fix issues.
Fixes #
```other operator
NONE
```
=> add linting check for deprecated functions

charts/internal/shoot-system-components/charts/aws-custom-route-controller/templates/role.yaml
/platform aws
Allow the aws-custom-route-controller to create events, e.g. on leader election.
Fixes #
```other operator
Allow the aws-custom-route-controller to create events on leader election.
```
=> Allow aws-custom-route-controller to create events 

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
/platform aws
The validation of the `InfrastructureConfig` has been extended by a duplicate name check in `spec.network.zones`
Fixes #643 
```other operator
Check for duplicate zone names in infrastructureconfig
```
=> Check for duplicate zone names in infrastructureconfig

charts/images.yaml
/area security
/platform aws
Add CVE categorisation/runtime contexts for managed OCI images of `MCM` and `mcm-provider-aws`.
Fixes #
```other operator
NONE
```
=> Add CVE runtime context for `MCM` and `mcm-provider-aws`

pkg/controller/healthcheck/add.go, pkg/controller/healthcheck/customroutecontrollerhealth.go
/platform aws
The aws-custom-route-controller creates events on successful or failed route updates with [PR #8](https://github.com/gardener/aws-custom-route-controller/pull/8).
These events are evaluated with a new health check and reported for the shoot condition type `ControlPlaneHealthy` on failure.
Fixes #
```other operator
Add health check for aws-custom-route-controller route updates
```
=> Health check for aws-custom-route-controller route updates

charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshots.yaml
/area storage
/kind bug
/platform aws
This PR copies the legacy CRDs in `charts/internal/shoot-system-components/charts/csi-driver-node/templates` (updated by PR #666) to `charts/internal/shoot-crds/charts/volumesnapshots/templates` and marks the legacy with `resources.gardener.cloud/mode=Ignore` again.
Fixes #696 
similar to https://github.com/gardener/gardener-extension-provider-openstack/pull/566
```other operator
A bug has been fixed that caused the `snapshot.storage.k8s.io` CRDs in shoot clusters to flap between two different versions.
```
=> Fix flapping snapshot.storage.k8s.io CRDs

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
This PR adds the `node.gardener.cloud/critical-component` label to `csi-driver-node` DaemonSet introduced in https://github.com/gardener/gardener/pull/7406 
Part of  https://github.com/gardener/gardener/issues/7117
https://github.com/gardener/gardener/pull/7406 is merged
```feature user
`csi-driver-node` is marked as a node-critical component. With this, workload pods are only scheduled to a `Node` if it runs a ready `csi-driver-node` pod.
```
=> Mark csi-driver-node as node-critical component

pkg/controller/bastion/options.go, test/integration/bastion/bastion_test.go
/kind bug
/platform aws
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/694
```other operator
add 't4g.nano' and arm64 type instance supported in the bastion instance
```
=> add arm64 type for bastion instance

charts/internal/shoot-storageclasses/templates/storageclasses.yaml
/area storage
/kind bug
/platform aws
Currently the defaulting logic for VolumeSnapshotClass for a VolumeSnapshot does not work because the annotation value is “true” and not "true" (note the wrong quotes).
**Steps to reproduce**:
1. Create a PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: ebs-claim
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
name: app
spec:
containers:
- name: app
image: centos
command: ["/bin/sh"]
args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
volumeMounts:
- name: persistent-storage
mountPath: /data
volumes:
- name: persistent-storage
persistentVolumeClaim:
claimName: ebs-claim
``` …
=> Fix the annotation value for `snapshot.storage.kubernetes.io/is-default-class`

.ci/pipeline_definitions
/area delivery
/platform aws
Similar to https://github.com/gardener/gardener-extension-provider-azure/pull/618
Fixes #
```other operator
NONE
```
=> Switch to the docker-buildx oci-builder

charts/internal/machineclass/templates/machineclass.yaml, pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/infrastructure/templates/main.tpl.tf, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area security
/kind bug
/platform aws
This PR removes `sshKeyName` from the `terraformInfraConfig` and `machineConfig` when `sshAccess` is disabled for the worker nodes. Disabling `sshAccess` stops the `keyPair` rotation and removes the current `sshPublicKey`. Currently `aws` `shoots` cannot be created with `sshAccess` disabled.
Fixes [gardener/gardener#7481](https://github.com/gardener/gardener/issues/7481)
This Draft depends on the changes in [this PR](https://github.com/gardener/machine-controller-manager-provider-aws/pull/104) and will remain in draft until the PR is merged and a new release is made. …
=> Fix `shoot` reconciliation when `sshAccess` is disabled.

charts/gardener-extension-admission-aws/charts/runtime/templates/service.yaml, charts/gardener-extension-admission-aws/values.yaml
/area high-availability
/platform aws
The following Service is adapted to be topology-aware:
- `gardener-extension-admission-aws` - the Service is consumed by `virtual-garden-kube-apiserver` and `gardener-apiserver` for the webhook communication
Part of https://github.com/gardener/gardener/issues/6718
N/A
```other operator
The `gardener-extension-admission-aws` Service in the `gardener-extension-admission-aws` chart can now be configured to be topology-aware.
```
=> Make the `gardener-extension-admission-aws` Service topology-aware

pkg/controller/controlplane/valuesprovider.go
/area quality
/kind bug
/platform aws
https://github.com/gardener/gardener-extension-provider-aws/pull/666 introduces the following issue:
We noticed that Seeds' SystemComponents condition are constantly flapping with error:
```
Required ClusterRole "extensions.gardener.cloud:provider-aws:csi-snapshot-validation" in namespace "" is missing
```
The above mentioned PR introduces adds the `extensions.gardener.cloud:provider-aws:csi-snapshot-validation` ClusterRole and ClusterRoleBinding to the Shoot cluster. But it also adds https://github.com/gardener/gardener-extension-provider-aws/blob/e12c20f1ff0c56cbaaf8526fbc8cfae64262c6de/pkg/controller/controlplane/valuesprovider.go#L173-L174 to the …
=> Do not delete `csi-snapshot-validation` ClusterRole and ClusterRoleBinding from the wrong cluster (Seed cluster) when deleting Shoot

pkg/aws/client/client.go
/area backup
/area security
/area compliance
/kind task
/platform aws
This PR configures the newly created S3 buckets to be blocked from public access as per standard practices. This is achieved by putting a public-access-block on the created bucket, as per [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-public-access-block.html).
Fixes #
cc @vlerenc 
```other operator
Block public access for newly created S3 buckets.
```
=> Block public access to S3 bucket as per standard practices

pkg/controller/healthcheck/add.go
This reverts commit edfc0252b4f6a9170de17eb40bdc807609830589.
/platform azure
`healthCheckResult` can be nil, if for some reason node listing fails. Vedoring the new gardener version should fix the issue.
Fixes #
```other operator
Remove the error code check from `NodesChecker` to prevent nil pointer panic.
```
=> Revert "Consider errors from NodesChecker for finding user related issues"

charts/images.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-volume-modifier.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-volume-modifier.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/role-csi-volume-modifier.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-volume-modifier.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/serviceaccount.yaml, pkg/aws/types.go, pkg/controller/controlplane/valuesprovider.go
/platform aws
This PR upgrades the EBS CSI driver and installs one additional sidecar to allow live volume modifications.
(see: https://github.com/awslabs/volume-modifier-for-k8s and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1600)
Note that there are not much data for the new side-car so the requests/limits might change soon once we know more from operating it.
Fixes #
```other operator
Update ebs driver to `v1.19.0`
```
```feature user
Enable awslabs/volume-modifier-for-k8s by default
```
=> Update EBS driver

pkg/controller/infrastructure/templates/main.tpl.tf
/platform aws
Currently the terraformer's `deadlinePod` timeout is 15mins:
https://github.com/gardener/gardener-extension-provider-aws/blob/5f0d082c2fc02ae5fe9a22d7f02af84d05dce111/pkg/controller/infrastructure/actuator.go#L62-L68
On the other hand, the aws_internet_gateway's `create` and `delete` timeouts are 20mins:
https://github.com/hashicorp/terraform-provider-aws/blob/8af0bd79119df3f3f8e642b931b0281bef29bb39/internal/service/ec2/vpc_internet_gateway.go#L29-L33
Hence, for example for a `terraform destroy` the terraformer Pod will be deleted by the provider extension before the aws_internet_gateway delete timeout is exceeded and it reports why the aws_internet_gateway cannot …
=> Align the aws_internet_gateway timeout to terraformer's timeout

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
/kind bug
/platform aws
VPA and deployment container name mismatch is preventing the container to get adequate resources
Fixes #
```other operator
update aws-csi-volume-modifier in vpa
```
=> update `aws-csi-volume-modifier` in vpa

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
/kind bug
Cherry pick of #763 on release-v1.44.
#763: update `aws-csi-volume-modifier` in vpa
```bugfix operator
Fix the name of the aws-csi-volume-modifier container the in the respective VPA resource.
```
=> [release-v1.44] Automated cherry pick of #763: update `aws-csi-volume-modifier` in vpa

pkg/aws/client/client.go
/area backup
/kind bug
/platform aws
Adds handling for S3 bucket policy for different [AWS partitions](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html) (region groups) such as [China regions](https://aws.amazon.com/blogs/enterprise-strategy/getting-started-with-aws-services-in-aws-china-beijing-region-and-aws-china-ningxia-region/) and [AWS GovCloud (US) regions](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html).
Fixes #
```bugfix operator
Handle S3 bucket policy IAM ARN for China and GovCloud (US) regions.
```
=> Fix S3 bucket policy for different AWS partitions (region groups)

pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
/area quality
/platform aws
Improves the message returned to the user when cidr validation fails for `.networking.{pods,nodes,services}`.
Fixes #
```other operator
NONE
```
=> Improve msg when validating cidrs

pkg/aws/client/client.go
/area backup
/kind bug
Cherry pick of #766 on release-v1.44.
#766: Fix S3 bucket policy for different AWS partitions (region groups)
```bugfix operator
Handle S3 bucket policy IAM ARN for China and GovCloud (US) regions.
```
=> [release-v1.44] Automated cherry pick of #766: Fix S3 bucket policy for different AWS partitions (region groups)

charts/images.yaml
/platform aws
Same as https://github.com/gardener/gardener-extension-provider-openstack/pull/640
Fixes #
```other dependency
The following dependencies were updated:
- registry.k8s.io/sig-storage/csi-provisioner v3.4.0 -> v3.4.1
```
=> Patch external-provisioner to 3.4.1

charts/images.yaml
/kind bug
Cherry pick of #775 on release-v1.44.
#775: Upgrade machine-controller-manager
**Release Notes**:
``` bugfix operator github.com/gardener/machine-controller-manager #834 @ialidzhikov
Included `UnavailableReplicas` in determining if a machine deployment status update is needed
```
=> [release-v1.44] Automated cherry pick of #775: Upgrade machine-controller-manager

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go, vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go, vendor/github.com/gardener/gardener/pkg/utils/kubernetes/managedseed.go, vendor/modules.txt
/kind bug
/platform aws
This PR vendors github.com/gardener/gardener@v1.75.0 in order to adopt cherry-pick of https://github.com/gardener/gardener/pull/8059.
Part of https://github.com/gardener/gardener/issues/8058
N/A
```other operator
The following dependency is updated to adopt a fix for https://github.com/gardener/gardener/issues/8058:
- github.com/gardener/gardener: v1.71.0 -> v1.71.5
```
=> [release-v1.44] Vendor gardener/gardener@v1.71.5

pkg/controller/infrastructure/infraflow/context.go, pkg/controller/infrastructure/infraflow/reconcile.go, test/integration/infrastructure/infrastructure_test.go
/kind bug
/platform aws
The terraform templates have been adjusted in PR #717 to set the values for tags `kubernetes.io/role/elb` and `kubernetes.io/role/internal-elb` to `1` instead to `use`. The value `1` is required by the ALB (see [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/subnet_discovery/))
With this fix, this change is also done for the non-terraform infrastructure controller logic.
Fixes #
see https://github.com/gardener/gardener-extension-provider-aws/commit/a2988fb11daec0bd78423e22aab0345f2daf3ed1#diff-afc289f8d352f18cb669b37b6e50a550c93f0a42a2a6f143256c7aee9c778a17R167
**Release …
=> Infraflow: Fix tag value for elb roles

test/integration/bastion/bastion_test.go
/platform aws
add a "sustainable" way to get available image AMIs for the test 
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/713
```other operator
add a sustainable way to get available image AMIs for the test
```
/invite @kon-angelo
=> add getImageAMI for sustainable test

.ci/test-integration.sh
/area testing
/platform aws
Same as https://github.com/gardener/gardener-extension-provider-aws/pull/778/commits/36ad694fae256aad8938ca84aad3fb8b57bcc2b6 -> increate the timeout for the release pipeline to accomodate the newer tests.
Fixes #
```other operator
NONE
```
=> update timeout for release pipeline

cmd/gardener-extension-provider-aws/app/app.go
/area cost
/platform aws
By default, the controller-runtime caches all objects of kinds which are accessed.
On very large seeds caching secrets can consume GBs of memory.
Therefore it is better to disable caching of secret objects.
Fixes #
I made a small benchmark on an empty seed with 230 secrets (150 big secrets added to make differences more visibile).
Memory usage with caching of secrets:
```bash
$ k -n extension-provider-aws-zj2jw top po
NAME                                               CPU(cores)   MEMORY(bytes)
gardener-extension-provider-aws-6cb999694d-fnfhz   5m           202Mi …
```
=> No caching of secrets

charts/internal/seed-controlplane/charts/aws-load-balancer-controller/templates/deployment.yaml
/area security
/area compliance
/platform aws
This PR modifies the `aws-load-balancer-controller` deployment to use an AWS credentials file for authentication.
These changes are in sync with Kubernetes' STIG. See rule [242415](https://www.stigviewer.com/stig/kubernetes/2022-09-13/finding/V-242415) for more details.
Fixes #
```other operator
The `aws-load-balancer-controller` deployment now uses an AWS credentials file for authentication.
```
=> Modify the AWS Load Balancer Controller deployment to use an AWS credentials file for authentication.

README.md, charts/internal/aws-lb-readvertiser/charts/utils-templates/templates/_versions.tpl, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, docs/operations/operations.md, imagevector/images.yaml, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind cleanup
/platform aws
Drop support for kubernetes < 1.24 for AWS extension provider
Part of https://github.com/gardener/gardener/issues/8405
```breaking operator
`provider-aws` no longer supports Shoots or Seeds with Кubernetes version < 1.24.
```
=> Drop support for Shoots with Kubernetes version < 1.24

imagevector/images.yaml
/area storage
/kind bug
/platform openstack
Fixes https://github.com/kubernetes-csi/external-snapshotter/issues/927
```other operator
Update external-snapshotter to v6.3.1
```
=> Update external-snapshotter to v6.3.1

imagevector/images.yaml
/platform aws
Switch image registry for `aws-ebs-csi-driver` to `registry.k8s.io` to support IPv6.
Fixes #
```other operator
The registry of the aws-ebs-csi-driver image is switched from ECR (`public.ecr.aws`) to `registry.k8s.io` because the ECR does not support image pulls over IPv6.
```
=> Switch image registry for aws-ebs-csi-driver to support IPv6

imagevector/images.yaml
/kind bug
Cherry pick of #825 on release-v1.50.
#825: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.19.1->v0.19.2]
```other operator github.com/gardener/machine-controller-manager #866 @gardener-robot-ci-2
The default `machine-safety-orphan-vms-period` has been reduced from 30m to 15m.
```
```bugfix operator github.com/gardener/machine-controller-manager #866 @gardener-robot-ci-2
Removes `node.machine.sapcloud.io/not-managed-by-mcm` annotation from nodes managed by the MCM.
```
=> [release-v1.50] Automated cherry pick of #825: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.19.1->v0.19.2]

docs/usage/dual-stack-ingress.md
/platform aws
The `ControlPlaneConfig` in the example is not valid. 
N/A
N/A
```other operator
NONE
```
=> Fix example for ControlPlaneConfig with loadBalancerController

docs/usage/dual-stack-ingress.md, pkg/aws/client/client.go, pkg/aws/client/mock/mocks.go, pkg/aws/client/types.go, pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/infrastructure/configvalidator.go, pkg/controller/infrastructure/infraflow/reconcile.go, pkg/controller/infrastructure/templates/main.tpl.tf, test/integration/bastion/bastion_test.go, test/integration/infrastructure/infrastructure_test.go, test/integration/vpc.go
/platform aws
This PR add support to dual-stack ingress with bring-your-own VPC. Users must assign Amazon managed CIDR range to their VPC. 
Fixes # part of https://github.com/gardener/gardener-extension-provider-aws/issues/833
```feature user
dual-stack ingress with bring-your-own VPC is supported.
```
=> Add support to dual-stack ingress with bring-your-own VPC.

imagevector/images.yaml
/kind task
/platform aws
Bump aws-custom-route-controller from v0.7.0 to v0.8.0
Fixes #
```other operator
Bump aws-custom-route-controller from `v0.7.0` to `v0.8.0`
```
=> Bump aws-custom-route-controller from v0.7.0 to v0.8.0

cmd/gardener-extension-admission-aws/app/app.go
/area security
/kind bug
/platform aws
This PR rectifies the leader election for the admission controller (introduced with #844).
⚠️ Must be part of `v1.52` release.
/cc @MartinWeindel
```other operator
NONE
```
=> Fix leader election of admission controller

imagevector/images.yaml
/platform aws
Switch from public ecr to artifact registry to expose images also via IPv6. The PR depends on https://github.com/gardener/ci-infra/pull/982/files.
Fixes #
```other operator
Switch from public ecr to artifact registry for IPv6 support.
```
=> switch from public ecr to artifact registry for ipv6 support

imagevector/images.yaml
/platform aws
Revert: https://github.com/gardener/gardener-extension-provider-aws/pull/856
Fixes #
```other operator
NONE
```
=> Revert "switch from public ecr to artifact registry for ipv6 support"

imagevector/images.yaml
Add a small comment to the `images.yaml` to explain _why_ we copy the image and point to the central file that handles the copying in an automated fashion (for future updates).
Hopefully this avoids future erroneous reverts.
=> Add comment to images.yaml

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-volume-modifier.yaml
/kind bug
/platform aws
Adapt `aws-csi-volume-modifier` container in the `csi-driver-controller` deployment after the update to v0.1.3 (ref: https://github.com/gardener/gardener-extension-provider-aws/pull/855) as it is described in https://github.com/awslabs/volume-modifier-for-k8s/pull/14
Fixes #
No release notes as the update to v0.1.3 has not been released.
```other operator
NONE
```
=> Fix csi-volume-modifier deployment after update to v0.1.3

pkg/webhook/controlplane/ensurer.go
/kind cleanup
/platform aws
When I was working on the registry-cache extension, I noticed that in various components we create `appendUniqueFile` func to append a file to the OSC files. Then, I noticed that there is the `extensionswebhook.EnsureFileWithPath` func that does the same thing.
N/A
N/A
```other operator
NONE
```
=> Use `extensionswebhook.EnsureFileWithPath` instead of custom `appendUniqueFile` func

go.mod, go.sum, pkg/apis/aws/const.go, pkg/aws/client/client_route53.go, pkg/aws/client/mock/mocks.go, pkg/aws/client/types.go, pkg/controller/dnsrecord/actuator.go, pkg/controller/dnsrecord/actuator_test.go, test/integration/dnsrecord/dnsrecord_test.go
/platform aws
On creating a `DNSRecord` for a AWS load balancer, the requested `CNAME`  record was always mapped to an `A` alias target recordset only. 
With this PR, creation of  `A` and/or `AAAA` recordsets can be controlled with the annotation `dns.gardener.cloud/ip-stack`. Possible values for the annotation are `ipv4`, `ipv6`, and `dual-stack`. In this way, e.g. dual-stack load balancers for the apiserver can be supported.
Additionally, the list of canonical hosted zone IDs was updated with some newer AWS zones.
Fixes #
```other operator
[dnsrecords] AAAA alias targets for load balancers …
```
=> [dnsrecords] create AAAA alias targets for load balancers with IPv6 addresses

.test-defs/infrastructure-test.yaml, test/integration/dnsrecord/dnsrecord_test.go
/area testing
/kind bug
/platform aws
Fixes #
```other operator
NONE
```
=> Fix dnsrecord flag usage

test/integration/dnsrecord/dnsrecord_test.go
/area testing
/kind cleanup
/platform aws
The integration test case using a load balancer known to be IPv4 only is obsolete, as action is now relying on an annotation and not on the IP addresses of the load balancer itself.
There are separate test cases for all annotation values. This test, which was optional anyway, can be removed.
Followup of #847 
```other operator
NONE
```
=> Remove obsolete test for load balancer which is known to be IPv4 only

imagevector/images.yaml
from v2.24.0 to v2.25.0
/platform aws
Fixes #
```other operator github.com/gardener/terraformer #146 @kon-angelo
Update go -> v1.21.5
```
```other operator github.com/gardener/terraformer #146 @kon-angelo
Update alpine -> v1.29.0
```
=> Upgrade terraformer

pkg/controller/backupentry/actuator.go
/kind bug
/platform aws
This PR removes the `source-` prefix of the given `BackupEntry` when performing entry deletion
Part of https://github.com/gardener/gardener/issues/8730
```bugfix developer
`source-` prefix of `BackupEntry` name is being ignored when performing entry deletion
```
=> Remove `source-` prefix from `BackupEntry` name when performing entry detion

imagevector/images.yaml
/platform aws
Adopt new cloud-controller-manager patch releases.
N/A
```other operator
The following images are updated:
- registry.k8s.io/provider-aws/cloud-controller-manager: v1.25.14 -> v1.25.15
- registry.k8s.io/provider-aws/cloud-controller-manager: v1.26.10 -> v1.26.11
- registry.k8s.io/provider-aws/cloud-controller-manager: v1.27.5 -> v1.27.6
- registry.k8s.io/provider-aws/cloud-controller-manager: v1.28.4 -> v1.28.5
- registry.k8s.io/provider-aws/cloud-controller-manager: v1.29.1 -> v1.29.2
```
=> Adopt new cloud-controller-manager patch releases

test/integration/dnsrecord/dnsrecord_test.go, test/integration/infrastructure/infrastructure_test.go, test/integration/vpc.go
/area testing
/kind cleanup
/platform aws
Fixes some issues with the integration-tests after the recent update to our dependencies:
- rm mentions of MetaDNSRecordSet from tests as well
- do not check for exact structural equality in natGatewayAddress, rather only check the fields we are interested in.
- ensure that the order of operations for DNS-related VPC options matches the one required as per documentation.
=> Fix/Update infra-test

pkg/aws/client/client.go
/kind bug
/platform aws
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/837
Thanks @Kostov6 @dimitar-kostadinov 
```other operator
Fix the categorization of the error when a user-provided VPC was not found 
```
=> fix vpc not found classification on configvalidator

go.mod, go.sum
/kind bug
/platform aws
Cherry-pick of the changes in #926 from master to release-branch for `v1.54` (for release notes) + `make tidy / make generate`
```other operator
Bump github.com/gardener/external-dns-management from 0.18.4 to 0.18.5.
```
```bugfix operator
DNSRecord controller will not create ALIAS DNS records for AWS "us-gov" zones anymore.
```
=> Bump github.com/gardener/external-dns-management from 0.18.4 to 0.18.5 for rel v1.54.0

pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
/platform aws
Fixes #958
```other operator
Fix a bug in which the infrastructure flow reconciler would fail to complete when the shoot's sshAccess was disabled. The reconciler now properly reconciles and deletes the ssh keypair as needed.
```
=> delete ssh keypair when disabled

pkg/controller/bastion/options.go, pkg/controller/bastion/options_test.go, test/integration/bastion/bastion_test.go
/platform aws
Temporarily forces bastion image to have version 1312.x.x
Fixes #
```bugfix operator
Temporarily forces bastion image to have version 1312.x.x
```
=> Force bastion image version

charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/servicemonitor.yaml
This PR applies #974 to the release-branch for `v1.55` (required to properly transport release-notes)
/area monitoring
/kind bug
```bugfix operator
Fixes a monitoring configuration issue that caused false CCM-down alerts to fire.
```
=> Apply PR #974 to Release branch

pkg/controller/dnsrecord/actuator.go, pkg/controller/dnsrecord/actuator_test.go
/area quality
/kind bug
/platform aws
This PR changes the actuator so that it ignores aws error code `NoSuchHostedZone` on DNSRecord deletion and does not report is as configuration problem. Also adding some tests.
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/953
```noteworthy operator
Aws error code `NoSuchHostedZone` is now ignored on DNSRecord deletion
```
=> Ignore `NoSuchHostedZone` on DNSRecord deletion

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area quality
/kind bug
/platform aws
Replaces occurrences of the `+` character in values to the MachineClass label `operatingSystemVersion` with `_` as `+` is not a permitted character in Kubernetes labels.
Fixes #982 
```other operator
A problem with deploying MachineClasses that reference an operating system image whose version contains a `+` character was fixed. 
```
=> Replace occurrences of `+` in operating system labels for MachineClasses with `_`

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
/area storage
/kind bug
/platform aws
This PR removes the failing `preStop` lifecycle hook from the `node-driver-registrar` container in `csi-driver-node` daemonset.yaml. The distroless registrar image lacks `/bin/sh`, causing the hook to fail. Socket removal is now handled internally by the registrar, eliminating the need for the hook (see kubernetes-csi/node-driver-registrar#61).
This is https://github.com/gardener/gardener-extension-provider-gcp/pull/792 for AWS
```bugfix operator
Removed unnecessary preStop hook from `node-driver-registrar` in `csi-driver-node`, as socket removal is now handled internally by `node-driver-registrar`, resolving distroless image …
```
=> rm failing preStop hook

charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml, charts/gardener-extension-admission-aws/values.yaml
/platform aws
This PR enhances the admission chart by the option to set a `priorityClassName`.
Part of https://github.com/gardener/gardener/issues/9936.
```other operator
A `priorityClassName` can now be set for the admission deployment via the `gardener-extension-admission-aws` Helm chart.
```
=> [admission] Add `priorityClassName`

pkg/admission/validator/shoot.go
/kind cleanup
/platform aws
Cleanup leftover validation, code has been introduced in https://github.com/gardener/gardener-extension-provider-aws/commit/c2d8b3292fd27cae25c2fa3b10abf191c3d11939#diff-341af93ea91d0a1cfcaedd3f19b8bbcefda579a084daef873d7b4938d965d947R128-R138 and partly removed in https://github.com/gardener/gardener-extension-provider-aws/commit/ded95f74ea82855ed4265458f849ba99bc6da926#diff-341af93ea91d0a1cfcaedd3f19b8bbcefda579a084daef873d7b4938d965d947L130-L134
```other operator
NONE
```
=> Remove leftover from prior cleanup

imagevector/images.yaml
from v0.20.0 to v0.20.1
**Release Notes**:
```bugfix operator github.com/gardener/machine-controller-manager #928 @rishabh-11
Fixed a bug where the `Unitialised` error code was blocking machine deletion
```
=> Upgrade machine-controller-manager-provider-aws on release-branch

charts/internal/machineclass/templates/machineclass.yaml, charts/internal/machineclass/values.yaml, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/platform aws
This PR  takes the `architecture` field from worker and then inserts it in the machine class
Fixes Part of  #https://github.com/gardener/autoscaler/issues/122
```other operator
Inserts `architecture` from worker to the machine class
```
=> Inserts `Architecture`  from worker to machineclass

cmd/gardener-extension-provider-aws/app/app.go, pkg/cmd/options.go, pkg/webhook/controlplane/add.go
/platform aws
Part of issue https://github.com/gardener/gardener/issues/9864, followup for g/g PR #9981. Use `ObjectSelector` in controlplane webhook to limit mutator calls for unrelated resource changes.
Part of #9864
```other operator
Starting with gardenlet >= v1.98.0, use controlplane webhook object selector to limit mutator calls.
```
=> Add object selector to controlplane webhook with version constraint

.ci/test-integration.sh
/platform aws
This PR increases the timeout for integrations tests from 1h to 2h.
Recently the tests took around 50 minutes, but with the introduction of the flow tests we run into timeouts.
Fixes #
```other operator
None
```
=> Increase integration test timeout to 2h

pkg/controller/infrastructure/terraform.go
/area quality
/kind bug
/platform aws
Return error instead of nil in function `CleanupTerraformerResources`
Fixes #
```other bugfix
Fix error handling in terraformer cleanup resources function
```
=> Fix error handling

pkg/cmd/options.go, pkg/controller/infrastructure/infraflow/context.go, test/integration/infrastructure/infrastructure_test.go
/kind bug
/platform aws
Fixes #
```other operator
Correctly register infrastructure webhook with the controllerruntime manager
```
```other operator
Fix an issue where the infrastructure state was not properly transformed to the provider status. 
```
=> Fix issues with the AWS flow after last update

pkg/controller/infrastructure/actuator_migrate.go
/kind bug
/platform aws
Fixes #
```other operator
Fix an issue where terraformer artifacts would not be deleted during the control-plane-migration `migrate` phase.
```
=> fix controlplane migration case for the infrastructure resources

pkg/controller/infrastructure/actuator_migrate.go
/kind bug
Cherry pick of #1039 on release-v1.57.
#1039: fix controlplane migration case for the infrastructure resources
```other operator
Fix an issue where terraformer artifacts would not be deleted during the control-plane-migration `migrate` phase.
```
=> [release-v1.57] Automated cherry pick of #1039: fix controlplane migration case for the infrastructure resources

pkg/cmd/options.go, pkg/controller/infrastructure/infraflow/context.go, test/integration/infrastructure/infrastructure_test.go
/kind bug
Cherry pick of #1038 on release-v1.57.
#1038: Fix issues with the AWS flow after last update
```other operator
Correctly register infrastructure webhook with the controllerruntime manager
```
```other operator
Fix an issue where the infrastructure state was not properly transformed to the provider status. 
```
=> [release-v1.57] Automated cherry pick of #1038: Fix issues with the AWS flow after last update

cmd/gardener-extension-admission-aws/app/app.go, docs/usage/usage.md, pkg/admission/validator/credentialsbinding.go, pkg/admission/validator/credentialsbinding_test.go, pkg/admission/validator/webhook.go
/area security ipcei
/platform aws
/label ipcei/workload-identity
Part of https://github.com/gardener/gardener/issues/9586
```feature user
The admission webhook now validates `CredentialsBinding`s.
```
=> [GEP-26] CredentialsBinding validation via admission webhook

pkg/aws/client/client.go, pkg/controller/infrastructure/infraflow/reconcile.go, pkg/controller/infrastructure/templates/main.tpl.tf, test/integration/infrastructure/infrastructure_test.go
/platform aws
Enable `nat64` and `dns64` for IPv6 shoot clusters.
Fixes #
```other operator
Enable `nat64` and `dns64` for IPv6 shoot clusters.
```
=> support nat64 and dns64

pkg/controller/infrastructure/infraflow/reconcile.go
/area quality
/kind bug
/platform aws
Fix cleanup of routing table associations.
If no routing table association is found, we should also check in the routing table retrieved by the client.
Fixes #
```bugfix user
Fix cleanup of routing table associations
```
=> Fix routing table association deletion

pkg/apis/aws/validation/infrastructure.go, pkg/aws/client/client.go, pkg/aws/client/mock/mocks.go, pkg/aws/client/types.go, pkg/controller/infrastructure/flow_reconciler.go, pkg/controller/infrastructure/infraflow/context.go, pkg/controller/infrastructure/infraflow/reconcile.go, pkg/controller/infrastructure/templates/main.tpl.tf, pkg/controller/infrastructure/tf_reconciler.go, test/integration/infrastructure/infrastructure_test.go
/platform aws
Create an IPv6 CIDR reservation for the first nodes subnet that we find, use it as Service CIDR and write it to `Infra.Status.Networking`.
The CIDR of the VPC will be used as Node range and Pod range and written to `Infra.Status.Networking`.
Fixes #
```other operator
Create IPv6 ServiceCIDR and write IPv6 ranges to Infra.Status.Networking
```
=> Create IPv6 ServiceCIDR and write IPv6 ranges to `Infra.Status.Networking`

pkg/webhook/shoot/add.go, pkg/webhook/shoot/mutator.go
/area scalability
/platform aws
Add object selector to the shoot webhook so that it is not invoked on every ConfigMap CREATE/UPDATE request in the kube-system namespace in the Shoot but only for the `addons-nginx-ingress-controller` ConfigMap.
Part of https://github.com/gardener/gardener/issues/9864
N/A
```other operator
The shoot-webhook that mutates the `addons-nginx-ingress-controller` ConfigMap does now specify object selector. The webhook will now intercept only requests for the `addons-nginx-ingress-controller` ConfigMap.
```
=> Add object selector to the shoot webhook

pkg/apis/aws/helper/scheme.go, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/area quality
/kind bug
/platform aws
This PR introduces `InfrastructureConfigFromCluster` that extracts the infrastructureConfig from a cluster resource and uses it in `pkg/webhook/controlplane/ensurer.go` instead of an API call.
This fixes a issue where cluster force deletion may fail
```bugfix operator
An issue causing Shoot force deletion to fail because the control plane webhook failing to get the Infrastructure object from the Seed cluster is now fixed. The control plane webhook now reads the infrastructureConfig from the Shoot spec in the Cluster resource. Previously, it was fetching the Infrastructure object from the Seed …
```
=> Introduce `InfrastructureConfigFromCluster` and use it instead of API call

charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml, docs/usage/usage.md, pkg/admission/validator/shoot.go, pkg/admission/validator/shoot_test.go, pkg/apis/aws/helper/scheme.go, pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go
/kind api-change
/platform aws
Make the aws provider extension aware of the `CloudProfile` field and the option to provide `NamespacedCloudProfile` references in the `shoot.Spec.CloudProfile`.
See also [GEP-25](https://github.com/gardener/gardener/issues/9504) and [this PR](https://github.com/gardener/gardener/pull/10093).
Related to https://github.com/gardener/gardener/issues/9504
```feature user
Enable support for the field `shoot.Spec.CloudProfile` alongside `cloudProfileName` and enable the future use of `NamespacedCloudProfile`.
```
=> [GEP-25] Enable Shoot cloudProfile reference as complement to cloudProfileName

pkg/controller/controlplane/valuesprovider.go
/platform aws
`aws-custom-route-controller` is disabled for IPv6.
Fixes #
```other operator
`aws-custom-route-controller` is disabled for IPv6.
```
=> disable crc for ipv6

Dockerfile, charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml, docs/usage/usage.md, pkg/aws/types.go, pkg/controller/controlplane/valuesprovider.go
/area storage
/area delivery
/kind bug
/platform aws
SC Gardener landscapes require the aws csi-driver to run in legacyXFS mode. To do this the parameter needs to be configurable inside of the values.yaml file as well as added to the daemonset if aforementioned parameter is set to `True`.
Fixes #
Test manually. Paused the corresponding managed resource object, edited the csi-driver pod and its image for one of our cluster to use the `1.35.0` version. Then, edited the pod spec to include the extra legacyXFS patameter. The pod is running fine with no issues in legacyXFS mode.
```other operator
The following images …
```
=> SC Gardener aws-ebs-csi-driver image update

pkg/apis/aws/helper/scheme.go
/kind cleanup
/platform aws
In #1068, we pushed https://github.com/gardener/gardener-extension-provider-aws/compare/eec15e76a4a8701b62c53dc27ac573f401255f50..b1e406fe7aad165f30746e3bf616340bffb21639 to address https://github.com/gardener/gardener-extension-provider-aws/pull/1068#discussion_r1776785054. However the last rebase (ref https://github.com/gardener/gardener-extension-provider-aws/compare/b1e406fe7aad165f30746e3bf616340bffb21639..ea73612e83e2c28e687dccfc1aed0e64a3c5a07e) reverted these changes.
Later on the issue was fixed in https://github.com/gardener/gardener-extension-provider-aws/pull/1086.
This PR adds minor nits so that https://github.com/gardener/gardener-extension-provider-aws/pull/1086 gets the same …
=> Minor nits after wrong rebase in #1068

pkg/controller/infrastructure/infraflow/reconcile.go
/area quality
/kind bug
/platform aws
Fix flow: Ignore subnet not found in infra state while deleting routing table associations
Fixes #
`c.client.GetRouteTable` already ignores not found error.
```bugfix operator
Fix flow: Ignore subnet not found in infra state while deleting routing table associations
```
=> Fix route table association deletion

pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
/platform aws
We should check if routeTable is nil before accessing it's associations.
Fixes #
```bugfix operator
Fix missing nil check after getting route table
```
=> Fix nil check after getting route table

pkg/aws/client/client.go, pkg/aws/client/types.go, pkg/aws/client/updater.go, pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
/platform aws
Fixes #
```other operator
Fix an issue where the "0.0.0.0/0" route creation would fail if the nat-gateway was previously deleted.
```
=> Route table duplicate "0.0.0.0/0" rule creation

pkg/admission/validator/shoot_test.go, pkg/apis/aws/validation/shoot.go
/platform aws
Enforce restriction with regards to IPv6 support.
Fixes #
This check replace https://github.com/gardener/gardener/pull/10716.
```other operator
Added validation to allow only IPv6-only shoot clusters, but not dual-stack as it is not supported, yet.
```
=> Enforce restriction with regards to IPv6 support

pkg/admission/mutator/shoot.go, pkg/admission/mutator/shoot_test.go
/platform aws
Always enable AWS load balancer controller for clusters with IPv6.
AWS cloud controller manager only supports purely IPv4 load balancers. It will not work in IPv6-only environments and does not offer the full functionality in dual-stack environments. Therefore, this change always enabled the fully IPv6-capable AWS load balancer controller in case a shoot cluster with IPv6 is created.
Fixes #
```other operator
AWS load balancers controller is always enabled for IPv6-only and dual-stack shoot clusters.
```
=> Always enable AWS load balancer controller for clusters with IPv6

pkg/controller/infrastructure/infraflow/reconcile.go, pkg/controller/infrastructure/templates/main.tpl.tf
The purpose of the internal subnet is to deploy internal load balancers. Since a load balancer can only be deployed to a subnet that has an IPv4 range, we need to assign an IPv4 range to the internal subnet.
/kind bug
/platform aws
Fixes #
```other operator
Fixed an issue preventing the deployment of internal load balancers in IPv6-only shoots.
```
=> Add IPv4 address to internal subnet for IPv6 only shoots.

pkg/aws/client/client.go, pkg/controller/infrastructure/infraflow/delete.go
Cherry pick of #1109 on release-v1.58.
#1109: Ignore alreadyDetached errors when detaching
```other operator
Ignore alreadyDetached errors when detaching instead of erroring out
```
=> [release-v1.58] Automated cherry pick of #1109: Ignore alreadyDetached errors when detaching

pkg/controller/infrastructure/templates/main.tpl.tf, test/integration/infrastructure/infrastructure_test.go
Unfortunately, https://github.com/gardener/gardener-extension-provider-aws/pull/1108 breaks terraform deploy and integrations tests for IPv6.
/kind bug
/platform aws
Fixes #
```other operator
Fixed terraform deploy and integration tests for IPv6.
```
=> Fix terraform deploy and integration tests for IPv6.

test/integration/infrastructure/infrastructure_test.go, test/integration/vpc.go
/kind test
/platform aws
- Make VPC deletion of the test more robust
- Deletion of infra is needed to count a test as passed
- Deletion of infra occurs after each test (and not at the end of the suite)
Fixes #
```other operator
NONE
```
=> fix test cardinality

pkg/aws/client/client.go, pkg/aws/client/types.go
/area quality
/kind cleanup
/platform aws
Change ToPort and FromPort in SecurityGroupRule to int32.
Fixes #
```other operator
NONE
```
=> Change ToPort and FromPort in SecurityGroupRule to int32

cmd/gardener-extension-provider-aws/app/app.go, pkg/cmd/options.go, pkg/webhook/controlplane/add.go
/kind cleanup
/platform aws
Remove gardener version constraint for controlplane webhook object selector.
Followup cleanup to https://github.com/gardener/gardener/issues/9864.
```other operator
```
=> Cleanup object selector version constraint

pkg/admission/validator/shoot_test.go, pkg/apis/aws/validation/shoot.go
/platform aws
Allow dual-stack networking.
Fixes #
```other operator
Dual-stack networking, i.e. networks with IPv4 and IPv6, are allowed now.
```
/cc @DockToFuture @axel7born
=> Allow dual-stack networking

pkg/admission/mutator/namespacedcloudprofile.go, pkg/admission/mutator/namespacedcloudprofile_test.go, pkg/admission/mutator/webhook.go, pkg/admission/validator/namespacedcloudprofile.go, pkg/admission/validator/namespacedcloudprofile_test.go, pkg/admission/validator/webhook.go, pkg/apis/aws/validation/cloudprofile.go
/platform aws
Support custom machine images and versions in `NamespacedCloudProfile`s. For that, add mutating and validating admission webhooks.
Part of https://github.com/gardener/gardener/issues/9504, followup to https://github.com/gardener/gardener/pull/10629.
/cc @timuthy 
```other operator
Add `NamespacedCloudProfile` admission mutation and validation to support custom machine images and types.
```
=> Add `NamespacedCloudProfile` validation and mutation webhooks

docs/usage/usage.md
/kind cleanup
/platform aws
The main change of this PR is the following commit:
https://github.com/gardener/gardener-extension-provider-aws/commit/e1eee828ff8f2664c51753cb708a23c18d6b63e3
The section [Node-specific Volume Limits](https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage/usage.md#node-specific-volume-limits) describes annotating the `Shoot` and emphasizes that this requires a manual reconciliation if the change should be applied immediately.
The section below, [Other CSI options](https://github.com/gardener/gardener-extension-provider-aws/blob/master/docs/usage/usage.md#other-csi-options), describes a `Shoot` annotation as well without …
=> docs: Repeat notice of manual shoot reconciliation

pkg/controller/infrastructure/infraflow/reconcile.go
Using IPv6 CIDR in ID string will break the migration of subnets from IPv4 to dual-stack. Due to the different ID, subnets would be deleted and crated again. This already breaks the migration of IPv4 shoots to shoots with dual-stack ingress.
/kind bug
/platform aws
Fixes #
```bugfix user
Use ipv6 CIDR in ID string only for IPv6 only subnets.
```
=> Use ipv6 CIDR in ID string only for IPv6 only subnets.

pkg/controller/infrastructure/infraflow/reconcile.go
Using IPv6 CIDR in ID string will break the migration of subnets from IPv4 to dual-stack. Due to the different ID, subnets would be deleted and crated again. This already breaks the migration of IPv4 shoots to shoots with dual-stack ingress.
/kind bug
/platform aws
Fixes #
```bugfix user
Use ipv6 CIDR in ID string only for IPv6 only subnets.
```
=> [Release v1.59] Fix subnet migration patch

pkg/admission/mutator/shoot.go, pkg/admission/mutator/shoot_test.go
/platform aws
In the past there have been issues with using TCP for upstream DNS requests on AWS. The AWS infrastructure does not handle lots of TCP connections for DNS queries well and the cluster may run into rate throttling leading to "connection timeout" issues during DNS resolution.
To avoid users having to manually set the `spec.SystemComponents.NodeLocalDNS.ForceTCPToUpstreamDNS` property for AWS, this PR sets a default value (false) if the property is not set on the shoot. This will make the shoot use UDP for upstream DNS by default and should prevent the issue from the start.
```other user
Shoots with NodeLocalDNS enabled will use UDP instead of TCP for …
```
=> fix: use UDP for upstream DNS by default

pkg/admission/mutator/webhook.go
/kind bug
/platform aws
Cherry-pick of https://github.com/gardener/gardener-extension-provider-aws/pull/1169.
```bugfix user
Fix the `NamespacedCloudProfile` status mutation.
```
=> [cherry-pick: v1.59] Use Subresource to mutate NamespacedCloudProfile status

charts/internal/seed-controlplane/charts/aws-ipam-controller/templates/deployment.yaml, charts/internal/seed-controlplane/charts/aws-ipam-controller/values.yaml, imagevector/images.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/platform aws
Set `primary-ip-family` flag for `aws-ipam-controller`
Fixes #
Requires: https://github.com/gardener/aws-ipam-controller/pull/83 which is in updated aws-ipam-controller image.
```other operator
Set `primary-ip-family` flag for `aws-ipam-controller`
```
=> set primary-ip-family flag for aws-ipam-controller

pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
/platform aws
With  https://github.com/gardener/gardener-extension-provider-aws/pull/1158 we use the IPv4 range for the subnet ID if present. 
However, the worker subnet is created as IPv6 only subnet without IPv4 range. During reconciliation, the worker subnet is considered as missing though a subnet with the required IPv6 range exists. 
With this change, we use an empty string as IPv4 CIDRBlock, even if the range is configured in the spec.
Fixes #
```bug user
Fixes an issue, where reconciliation of IPv6 shoots fails, when an IPv4 range for the worker subnet is configured.
```
=> Set IPv4 CIDR to empty string for IPv6 only shoots.

pkg/apis/aws/validation/infrastructure.go
/platform aws
Adds validation of the `ìnternal`-subnet CIDR in case of IPv6 (as required per documentation).
```other operator
Add validation of internal-subnet CIDR for IPv6 shoots
```
=> Fix IPv6 validation

cmd/gardener-extension-provider-aws/app/app.go, pkg/cmd/options.go, pkg/webhook/seedprovider/add.go, pkg/webhook/seedprovider/ensurer.go, pkg/webhook/seedprovider/ensurer_test.go
/kind cleanup
/platform aws
Rename packages, loggers and variables according to the new name.
Which issue(s) this PR fixes:
Followup renaming of https://github.com/gardener/gardener/issues/10017.
```other operator
NONE
```
=> Rename to `seedprovider` webhook

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-resizer.yaml, docs/usage/usage.md, pkg/aws/types.go, pkg/controller/controlplane/valuesprovider.go
/platform aws
Adds support for setting the necessary featuregate required when using VolumeAttributesClasses.
Fixes #
```feature user
Support for VolumeAttributesClasses can now be enabled via shoot annotation.
```
=> Add support for VolumeAttributesClasses

pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
…deletion
/kind cleanup
/platform aws
This PR removes the obsolete deletion of the `csi-driver-controller-observability-config` `ConfigMap`.
The `TODO` comment indicates that the code should be removed in a future release.
It was introduced with: https://github.com/gardener/gardener-extension-provider-aws/commit/ef1530cde26fa3a224f260e8e13f67dfbf0d995b
The change first appeared in the release:
https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.43.0
At the time of writing, the latest release is:
https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.60.0
_n.a._
_n.a._
**Release …
=> chore: Cleanup obsolete `csi-driver-controller-observability-config` deletion

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind cleanup
/platform aws
This PR cleans up the deprecated label approach for defining network policies.
The first of these labels was introduced here:
https://github.com/gardener/gardener-extension-provider-aws/commit/9fbf711930ecd37ac4995541efe56b7bc476ebab
See the corresponding PR for more context:
https://github.com/gardener/gardener/pull/7907
_n.a._
_Uncertainty:_
I can find the annotation that replaces the deprecated label `networking.resources.gardener.cloud/to-csi-snapshot-validation-tcp-443=allowed`:
https://github.com/gardener/gardener-extension-provider-aws/blob/fe0e6d93c22c56d8ca4ce394d3ae7fa41863b555/charts/inter …
=> chore: Cleanup deprecated label approach

README.md, imagevector/images.yaml
/area open-source usability
/platform aws
/exp intermediate
/topology garden seed shoot
/merge squash
This PR adds support for Kubernetes 1.32 to the extension.
Part of https://github.com/gardener/gardener/issues/11020
* I have successfully validated the functionality as follows:
```feature user
The provider-aws extension does now support shoot clusters with Kubernetes version 1.32. You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.32.md) before upgrading to 1.32.
```
=> Add Kubernetes 1.32 support

imagevector/images.yaml
/kind bug
Cherry pick of #1159 on release-v1.59.
#1159: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.21.0->v0.22.0]
```bugfix operator github.com/gardener/machine-controller-manager-provider-aws #180 @renormalize
Fixed a panic that occurs while fetching the status of a VM backing a machine from the provider.
```
```other operator github.com/gardener/machine-controller-manager-provider-aws #179 @thiyyakat
Added `gosec` for Static Application Security Testing (SAST).
```
```other developer github.com/gardener/machine-controller-manager-provider-aws #179 @thiyyakat
The `gardener/machine-controller-manager` dependency has been updated to `v0.55.1`. [Release Notes](https://redirect.github.com/gardener/machine-controller-manager/releases/tag/v0. …
```
=> [release-v1.59] Automated cherry pick of #1159: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.21.0->v0.22.0]

pkg/admission/validator/cloudprofile.go, pkg/admission/validator/namespacedcloudprofile.go, pkg/apis/aws/validation/cloudprofile.go, pkg/apis/aws/validation/cloudprofile_test.go
/area quality
/platform aws
This PR adjusts the CloudProfile validation so that all MachineImages in the CloudProfile map to a valid image in the CloudProfileConfig.
Follow up to https://github.com/gardener/gardener-extension-provider-azure/pull/1020.
Fixes #
```other operator
Validate that all MachineImages in the CloudProfile map to a valid MachineImage in the CloudProfileConfig
```
=> Fix CloudProfile MachineImages validation

docs/tutorials/kubernetes-cluster-on-aws-with-gardener/kubernetes-cluster-on-aws-with-gardener.md
/platform aws
Replaced shortcodes with improved Hugo blockquote syntax.
This way, notes will be rendered the same way in GitHub and the websites.
Fixes #
```doc developer
NONE
```
=> Replaced shortcodes

charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml
/area security
/kind bug
/platform aws
Fixes permissions. The validator webhook requires GET permissions over workload identities. https://github.com/gardener/gardener-extension-provider-aws/blob/7b03c432a2935b6d24a5ddf0cb7f8750cd9cf07b/pkg/admission/validator/credentialsbinding.go#L69-L71
Can we merge this before the next release of the provider?
cc @kon-angelo 
Fixes #
```bugfix operator
NONE
```
=> Allow admission to get workloadidentities

.ci/component_descriptor
/area delivery
/platform aws
Fixes #
```other operator
Update component-descriptor script to include external images again
```
=> Reintroduce external image upload to cd script.

README.md
/kind task
/platform aws
It adds the conformance test results badge for Kubernetes v1.32.
Part of: https://github.com/gardener/gardener/issues/11020
/cc @LucaBernstein 
```other operator
NONE
```
=> docs: Add conformance test results badge for Kubernetes v1.32

pkg/controller/bastion/actuator_reconcile.go, pkg/controller/bastion/options.go
/platform aws
Fixes #
```other operator
Add IPv6 address to bastion VM for IPv6 shoots
```
=> Add IPv6 address to bastion VM for IPv6 shoots.

docs/usage/ipv6.md, pkg/apis/aws/validation/shoot.go
/platform aws
Improve Documentation and Admission Checks for IPv6/Dual-Stack and Pod Overlay Network.
Previously, it was possible to directly try to migrate an IPv4-only cluster with pod overlay network. This results in a non-working cluster with a broken pod network. Therefore, we now prevent the dual-stack migration unless the cluster is already working in native routing mode, i.e. unless the overlay network was disabled.
In addition to that, the IPv6 documentation is updated to reflect the fact that dual-stack migration is now possible.
Fixes #
```other operator
Enabling IPv6 without disabling …
```
=> Improve Documentation and Admission Checks for IPv6/Dual-Stack and Pod Overlay Network.

imagevector/images.yaml
/kind bug
Cherry pick of #1299 on release-v1.61.
#1299: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.23.0->v0.24.0]
```other operator github.com/gardener/machine-controller-manager #981 @takoverflow
Resource exhaustion on machine creation results in a longer retry period
```
```bugfix operator github.com/gardener/machine-controller-manager #964 @takoverflow
A new termination queue to handle machines scheduled for deletion introduced to separate creation requests from deletion
```
```bugfix operator github.com/gardener/machine-controller-manager #985 @renormalize
machine-controller-manager version, and build information are printed at startup.
```
```other operator github.com/gardener/machine-controller-manager #968 @takoverflow …
```
=> [release-v1.61] Automated cherry pick of #1299: [ci:component:github.com/gardener/machine-controller-manager-provider-aws:v0.23.0->v0.24.0]

.github/workflows/build.yaml, .github/workflows/release.yaml
/area delivery
/kind bug
/platform aws
Fixes #
```other operator
```
=> fix: correctly reference reusable release-workflow

imagevector/images.yaml
/area quality
/platform aws
Update csi images:
csi-attacher: v4.8.0 -> v4.8.1
csi-resizer: v1.13.1 -> v1.13.2
csi-snapshotter: v8.2.0 -> v8.2.1
csi-snapshot-controller: v8.2.0 -> v8.2.1
Fixes #
```other dependency
Update csi images:
csi-attacher: v4.8.0 -> v4.8.1
csi-resizer: v1.13.1 -> v1.13.2
csi-snapshotter: v8.2.0 -> v8.2.1
csi-snapshot-controller: v8.2.0 -> v8.2.1
```
=> Update csi images

cmd/gardener-extension-provider-aws/app/app.go, cmd/gardener-extension-provider-aws/app/migrations.go
/area security
/kind cleanup
/platform aws
After the Machine Controller Manager was moved from the provider extension codebases to the core, the charts that define the component's resources have been deleted, as well as most resources that have been deployed to that point - [PR reference](https://github.com/gardener/gardener-extension-provider-aws/pull/872/files).
However, some ClusterRoles and ClusterRoleBindings that were used for the component still remain on certain seeds.
This PR adds a function to purge those, since they are not in use anymore.
The ClusterRoles|ClusterRoleBindings in question are named in the following way:
```
extensions.gardener.cloud:provider-aws:<shoot-name>:machine-controller-manager
``` …
=> Purge unused Machine Controller Manager RBAC resources

example/30-worker.yaml, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/platform aws
Data volumes are also excluded from the hash calculation for in-place updates similar to provider config.
Part of https://github.com/gardener/gardener/issues/10219
Follow-up of https://github.com/gardener/gardener-extension-provider-aws/pull/1276
```other operator
NONE
```
=> Exclude data volumes from worker pool hash calculation for in-place updates

.github/workflows/build.yaml, .github/workflows/head-update.yaml
/area delivery
/kind bug
/platform aws
Fixes #
```other operator
fix: publish oci-images to previously used repositories
```
=> fix: publish oci-images to previously used repositories

test/integration/backupbucket/backupbucket_test.go, test/integration/backupbucket/helper_test.go
/area testing
/kind test
/platform aws
just a small fix that changes 2 const vars to not being exported anymore since it's not required.
Fixes #
=> change exported consts to unexported

.github/workflows/build.yaml, .ocm/base-component.yaml
As a left-over from migration from concourse-pipeline, gosec-report was no longer attached to Component-Descriptors. Add reports again for future releases.
Consider explicitly passing --report-fname to avoid hardcoding default name: https://github.com/gardener/gardener/pull/12274
/area delivery
/kind bug
/platform aws
Fixes #
```bugfix developer
add gosec-report to Component-Descriptor (again)
```
=> add gosec-report to ocm-component-descriptors

.ci/prepare_release, .github/actions/prepare-release/action.yaml, .github/workflows/build.yaml, .github/workflows/release.yaml
/area delivery
/kind bug
/platform aws
run `make generate` for release- and bump-commits (again)
As yet another left-over from migration to GitHub-Actions, run prepare-commit (make generate) for both release-commit, and bump-commit.
Fixes #
```other developer
run `make generate` for release- and bump-commits (again)
```
=> run `make generate` for release- and bump-commits

charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/webhook/cloudprovider/ensurer.go, pkg/webhook/cloudprovider/ensurer_test.go
/area quality
/kind bug
/platform aws
When using workload identity I observe the following error in cloud controller manager.
```
W0612 06:40:35.700604       1 instances_v2.go:90] Failed to get node topology. Moving on without setting labels: "operation error EC2: DescribeInstanceTopology, get identity: get credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region"
E0612 06:40:35.948326       1 topology.go:95] Error describing instance topology: "operation error EC2: DescribeInstanceTopology, get identity: get credentials: failed to refresh cached …
```
=> Set AWS_REGION for cloud controller manager

.ci/testruns/default/templates/testrun.yaml, .gitignore, .test-defs/backupbucket-test.yaml, test/integration/backupbucket/helper_test.go
/area testing
/kind test
/platform aws
This PR changes the backupbucket integration test from using the shoot-operator secret to using the newly created dedicated backup-operator secret to get the aws `s3.Client`.
In addition, a useless log message is removed and `.swp` files are added to `.gitignore`.
Fixes #
=> Use backup operator secret for backupbucket integration test

docs/operations/operations.md
/area security ipcei documentation
/platform aws
Update seed backup docs to use credentialsRef field
Fixes #
Part of https://github.com/gardener/gardener/issues/9586
x-ref: https://github.com/gardener/gardener/pull/12347#discussion_r2160947091
cc @dimityrmirchev
```other operator
NONE
```
=> [GEP-26] Update seed backup docs to use credentialsRef field

.github/workflows/run-integrationtests.yaml
/area delivery
/kind task
/platform aws
Fixes #
```other developer
add GitHub-Action-Workflow for running testmachinery-tests (again) to thus finalise migration from Concourse-Pipelines to GitHub-Actions.
```
=> add job for running testmachinery-tests (again)

.ci/prepare_release, .github/actions/prepare-release/action.yaml, .github/workflows/build.yaml, .github/workflows/release.yaml
/area delivery
/kind bug
Cherry pick of #1365 on release-v1.62.
#1365: run `make generate` for release- and bump-commits
```other developer
run `make generate` for release- and bump-commits (again)
```
=> [release-v1.62] Automated cherry pick of #1365: run `make generate` for release- and bump-commits

hack/api-reference/api.md, pkg/apis/aws/types_infrastructure.go, pkg/apis/aws/v1alpha1/types_infrastructure.go, pkg/apis/aws/v1alpha1/zz_generated.conversion.go, pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go, pkg/apis/aws/validation/infrastructure.go, pkg/apis/aws/validation/infrastructure_test.go, pkg/apis/aws/zz_generated.deepcopy.go, pkg/aws/client/client.go, pkg/aws/client/types.go, pkg/controller/infrastructure/infraflow/reconcile.go
/platform aws
Add the option to configure [dedicated tenancy](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/change-tenancy-vpc.html) for a gardener-managed VPC using a new property `enableDedicatedTenancyForVPC`.
Fixes #1377 
* This PR introduces the property as immutable, you can set this only on VPC creation. Technically, AWS allows for _disabling_ this on an existing VPC, but there is no way back: enabling on an existing VPC is forbidden. But this seems dangerous, as it allows you to remove an important compliance configuration when there is no way back.
* While the property on AWS level is a simple …
=> Support for configuring dedicated tenancy for VPC

pkg/aws/client/client.go
/area audit-logging
/platform aws
Adds information to the UserAgent string of the created client to make it easier to identify calls made by clients created by the extension provider.
Fixes #
```other operator
Clients created by the AWS extension provider will now identify themselves by adding to the `user-agent` header of their calls.
```
=> Set user agent when creating AWS clients

cmd/gardener-extension-provider-aws/app/migrations.go
/area compliance
/kind cleanup
/kind bug
/platform aws
With the [following PR](https://github.com/gardener/gardener-extension-provider-aws/pull/1315), a migration runnable has been added to clean up leftover `ClusterRoles` that are not used anymore.
The obsolete `ClusterRoles` in question can be named in the following format:
`extensions.gardener.cloud:provider-aws:shoot--<namespace>--<shoot_name>:machine-controller-manager` 
However, the runnable logic does not take into account that for older installations, the `ClusterRole` could be named with a singular dash separator:
`extensions.gardener.cloud:provider-aws:shoot-<namespace>-<shoot_name>:machine-controller-manager` 
This PR adjusts the regex to accept both name …
=> Update the regex selector for the unused MCM RBAC resources

pkg/apis/aws/validation/infrastructure.go
/area quality
/kind cleanup
/platform aws
On AWS, some Shoots contain duplicate zone entries in their infraConfig.
This issue could only occur in older Shoots, created before a validation rule was introduced several years ago.
At the time, Terraformer did not flag this duplication, but the current flow reconciler is unable to handle it properly.
As a result, we need to remove these duplicate entries to ensure smooth reconciliation
Fixes #
```other operator
Allow deletion of duplicated zones in infraConfig section
```
=> Allow deletion of duplicated zones

pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
/platform aws
Due to the static IPv6 CIDR calculation subnets of multiple shoots get the same CIDR and the creation fails for all but one shoot. This PR retries the subnet creation with the next /64 CIDR block in case of an `InvalidSubnet.Conflict` error.
Fixes #
```bug user
Now it is possible to create more than shoot with IPv6 networking in the same VPC.
```
=> Allow creation or more that one IPv6 shoot in one VPC

.github/workflows/head-update.yaml
/platform aws
Adds label-based trust to the head update build job so oci artifacts can be published from PRs of forked repos.
PRs with the label `reviewed/ok-to-test` will publish their build results. 
@AndreasBurger
=> Add label-based trust to head-update build job

.github/workflows/build.yaml
/platform aws
adds pull-request write permissions to GH actions build workflow.
PRs with the label `reviewed/ok-to-test` will publish their build results. 
fix for: https://github.com/gardener/gardener-extension-provider-aws/pull/1452
@AndreasBurger
=> Add label bases trust to build workflow

hack/api-reference/api.md, pkg/admission/validator/cloudprofile.go, pkg/admission/validator/namespacedcloudprofile.go, pkg/admission/validator/shoot.go, pkg/admission/validator/shoot_test.go, pkg/apis/aws/helper/capabilities.go, pkg/apis/aws/helper/helper.go, pkg/apis/aws/helper/helper_test.go, pkg/apis/aws/types_cloudprofile.go, pkg/apis/aws/types_worker.go, pkg/apis/aws/v1alpha1/types_worker.go, pkg/apis/aws/v1alpha1/zz_generated.conversion.go, pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go, pkg/apis/aws/validation/cloudprofile.go, pkg/apis/aws/validation/cloudprofile_test.go, pkg/apis/aws/validation/worker.go, pkg/apis/aws/zz_generated.deepcopy.go, pkg/controller/worker/machine_images.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/webhook/infrastructure/mutate.go
/platform aws
This PR is part of [GEP-33 Machine Image Capabilities](https://github.com/gardener/gardener/blob/master/docs/proposals/33-machine-image-capabilities.md)
To make use of the introduced machine `Capabilities`. This PR implements the AMI selection based on these `Capabilities`. The selection algorithm distinguishes if a shoot is created based on a `CloudProfile` with or without `Capabilities` to select the best matching AMI for an `MachineImageVersion`. It also ensures that the status of `Workers` is consistently using `Capabilities` or not to support switching existing `Workers` to a `Cloudprofile` with `Capabilities` and the other way round.
**Which issue(s) this PR …
=> [GEP-33] Capabilities based MachineClass creation

imagevector/images.yaml
/area quality
/platform aws
This PR updates the AWS EFS CSI driver image to v2.1.12.
The release notes mention no breaking changes.
Fixes #
```other operator
Update EFS CSI driver image to v2.1.12
```
=> `chore:` Update EFS CSI driver image to v2.1.12

.github/workflows/close-milestone.yaml, .github/workflows/release.yaml
/area quality
/platform aws
This PR adds a close-milestone GitHub action workflow that's called at the end of a release action.
With that release milestones are closed automatically after a release.
Fixes #
```other operator
NONE
```
=> Automatically close release milestones
