- pkg/controller/infrastructure/actuator_delete.go
Currently we early exit If there is no given  output variables in the terraform.tfstate. However there might be still important resources in the tfstate which are there and we should not early exit depending on variable presence.
Also terraform destroy discards the output variables on state update no matter if resource is still there or not.
Fixes #
```improvement operator
The infrastructure controller does no longer release the finalizer of Infrastructure CR if it cannot find a given output variables. This allows terraform destroy to be invoked even when there is no output variables in the terraform.tfstate.
```
> Prevent infra controller to exit when there is still state

- .ci/testruns/default.yaml
- .ci/tm-config.yaml
Add TestMachineryBot and testrun definition for infrastructure tests
cc @dguendisch @AndreasBurger 
```improvement operator
NONE
```
> Integrate testrun and tm bot

- docs/usage-as-end-user.md
Add statement in the documentation that custom VPCs needs properly enabled DNS support.
Fixes #
```improvement operator
NONE
```
> improve documentation for custom vpc

- test/integration/infrastructure/infrastructure_test.go
/area testing
/platform aws
As discussed in https://github.com/gardener/gardener/issues/2272, cleanup logic in a `defer` won't be called if the test execution is interrupted. This PR adapts the infrastructure test to have its cleanup in AfterSuite to address this issue.
Fixes #
```improvement operator
NONE
```
> Move cleanup logic in AfterSuite

- Dockerfile
- test/integration/infrastructure/infrastructure_test.go
/kind cleanup
/platform aws
Remove unnecessary err check.
```improvement operator
NONE
```
> Nit: Remove unnecessary err check

- charts/images.yaml
/area storage
/kind task
/platform aws
Update amazon/aws-ebs-csi-driver to v0.7.0.
```improvement user
`amazon/aws-ebs-csi-driver` is now updated to `v0.7.0`.
```
> Update amazon/aws-ebs-csi-driver to v0.7.0

- charts/images.yaml
from v0.33.1 to v0.33.2
/area performance
/kind bug
/platform aws
This is a hotfix that helps with the throttling issues.
Refer- https://github.com/gardener/machine-controller-manager/releases/tag/v0.33.2
Fixes #
The corresponding hotfix has been merged in the master with [this PR](https://github.com/gardener/gardener-extension-provider-aws/pull/194) with MCM `v0.34.2`. This is the hotfix for the previous version MCM `v0.33.2`. 
```noteworthy operator
Introduced a backoff in re-enqueuing machines on creation/deletion failures. Avoids throttling APIServer & provider calls.
```
```improvement developer
Adds a new …
```
> Upgrade github.com/gardener/machine-controller-manager

- .landscaper/blueprint.yaml
- .landscaper/deploy_items.yaml
- .landscaper/imports.yaml
- .landscaper/registration/Chart.yaml
- .landscaper/registration/templates/cloudprofile.yaml
- .landscaper/registration/templates/controllerregistration.yaml
- .landscaper/registration/templates/secrets.yaml
- .landscaper/registration/values.yaml
/area delivery open-source
/platform aws
This PR adds the landscaper artifacts for this extension. It consists of a Helm chart that renders the `CloudProfile`, `ControllerRegistration`, `Secrets` and `SecretBinding`s based on the imports and inputs.
/invite @schrodit @Diaphteiros @dguendisch @mandelsoft 
```improvement operator
NONE
```
> Landscaper component

- docs/usage-as-end-user.md
Add documentation regarding rate limiting.
Outcome from: https://github.com/gardener/gardener/issues/3120
> Document rate limit issues

- charts/images.yaml
/priority critical
/platform aws
This MCM hotfix fixes issues with drain where machines were being force drained due to a race condition.
Fixes https://github.com/gardener/machine-controller-manager/issues/563
```noteworthy user
Fixes issues where machines were force deleted during normal deletion due to a race condition.
```
> Cherrypick PR#218 to release-v1.17

- charts/images.yaml
/priority critical
/platform aws
This MCM hotfix fixes issues with drain where machines were being force drained due to a race condition.
Fixes https://github.com/gardener/machine-controller-manager/issues/563
```noteworthy user
Fixes issues where machines were force deleted during normal deletion due to a race condition.
```
> Bump MCM version from 0.34.3 to 0.34.4

- README.md
> Update README.md with versions that are no longer actively tested

- pkg/apis/aws/validation/infrastructure.go
- pkg/apis/aws/validation/infrastructure_test.go
- pkg/validator/shoot_validator.go
/kind cleanup bug
/platform aws
After https://github.com/gardener/gardener-extension-provider-openstack/pull/204 this PR now slightly refactors the logic of validating the `.spec.provider.infrastructureConfig` of a `Shoot` against the constraints in the `CloudProfile`.
```bugfix operator
It is now possible to remove zones from the `CloudProfile` without breaking the possibility of adding new, still allowed zones to the `.spec.provider.infrastructureConfig` of `Shoot`s which are using the removed zone.
```
> Slightly refactor validation of infra config against CloudProfile

- charts/images.yaml
/platform aws
This PR fixes regressions W.R.T multi-disk support for EC2 instances using the MCM OOT. 
Fixes #
```bugfix user
Fixes regressions while supporting multiple volumes for EC2 instances
```
```other developer
Validation for block devices is now improved
```
> Cherrypick of PR#265 on release-v1.20

- charts/images.yaml
/kind bug
/platform aws
Cherry-pick https://github.com/gardener/gardener-extension-provider-aws/pull/274 on release v1.20
Fixes #
```bugfix operator
Allow deletion of machine whose providerID is empty.
```
> [release-v1.20] Upgrade github_com_gardener_machine-controller-manager-provider-aws from v0.4.0 to v0.4.1

- pkg/aws/client/client.go
/kind bug
/platform aws
Fixes #303
```bugfix user
An issue causing provider-aws to fail to delete Infrastructure when there are more than 20 LBs associated to the VPC is now fixed.
```
> Respect DescribeTagsInput constraints

- pkg/aws/client/client.go
/kind bug
Cherry pick of #304 on release-v1.22.
#304: Respect DescribeTagsInput constraints
```bugfix user
An issue causing provider-aws to fail to delete Infrastructure when there are more than 20 LBs associated to the VPC is now fixed.
```
> [release-v1.22] Automated cherry pick of #304: Respect DescribeTagsInput constraints

- pkg/controller/infrastructure/actuator.go
Decrease terraformer log level
> Decrease terraformer log level

- test/integration/infrastructure/infrastructure_test.go
/kind test
/platform aws
This PR tests https://github.com/gardener/terraformer/pull/93 and https://github.com/gardener/gardener/pull/3950 by adding an integration test case for invalid credentials.
It creates an infrastructure resource but uses invalid credentials and ensures that the `ERR_INFRA_UNAUTHORIZED` is correctly detected from the termination message and that the infrastructure can still be deleted afterwards (as it's a no-op).
Ref https://github.com/gardener/terraformer/issues/67
```other operator
NONE
```
> Add integration test case for invalid credentials

- cmd/gardener-extension-provider-aws/app/app.go
> Nit: Remove redundant import

- go.mod
- go.sum
- vendor/github.com/gardener/gardener/hack/.ci/prepare_release
- vendor/github.com/gardener/gardener/hack/test-cover-clean.sh
- vendor/github.com/gardener/gardener/hack/test-cover.sh
- vendor/github.com/gardener/gardener/hack/test-integration.sh
- vendor/github.com/gardener/gardener/hack/test-prometheus.sh
- vendor/github.com/gardener/gardener/hack/test.sh
- vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
- vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
- vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
- vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
- vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
- vendor/modules.txt
> Vendor gardener/gardener@v1.27.1

- .ci/testruns/default/templates/testrun.yaml
- .test-defs/dnsrecord-test.yaml
- Makefile
- pkg/aws/client/client_route53.go
- test/integration/dnsrecord/dnsrecord_suite_test.go
- test/integration/dnsrecord/dnsrecord_test.go
/kind test
/platform aws
Adds an integration test for the `DNSRecord` controller.
Fixes #
```other operator
NONE
```
> Add dnsrecord integration test

- pkg/apis/aws/validation/infrastructure.go
- pkg/apis/aws/validation/infrastructure_test.go
/area quality
/platform aws
Fail on validation when applying a shoot resource that contains a duplicate `elasticIPAllocationID`.
```other feature
fail during validation when `elasticIPAllocationID` is duplicated across zones
```
> Validate duplication of ElasticIPAllocationID

- charts/internal/machineclass/templates/machineclass.yaml
/area quality
/kind bug
/platform aws
This PR adds `srcAndDstChecksEnabled` to the MachineClass template.
Fixes #444 
I could not run the `make verify` locally due to some dependencies. Pardon the build failures if any.
```other operator
NONE
```
> Add `srcAndDstChecksEnabled` to the MachineClass template

- charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
/platform aws
Which issue(s) this PR fixes:
Part of gardener/gardener#4742
@ialidzhikov 
```other operator
NONE
```
> Update RBAC for leader election of machine-controller-manager

- .test-defs/bastion-test.yaml
- .test-defs/dnsrecord-test.yaml
- .test-defs/infrastructure-test.yaml
Similar to https://github.com/gardener/gardener/pull/5478
```other operator
NONE
```
> Replace -ginkgo.noColor with -ginkgo.no-color

- pkg/controller/dnsrecord/actuator.go
/platform aws
Please see https://github.com/gardener/gardener/pull/5551#discussion_r825935056
/invite @shafeeqes 
/cc @ialidzhikov 
```other operator
NONE
```
> Extend error code mapping

- charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
/kind bugfix
/platform aws
Fixes an incorrect value in the validator chart.
Fixes #
```other operator
NONE
```
> Fix incorrect validator deployment value

- charts/images.yaml
```feature dependency github.com/gardener/cloud-provider-aws $6e0c40b2ccadbe44167c9730f378faf28474d1b2
`k8s.io/legacy-cloud-providers` is now updated to `v1.21.12`.
```
```improvement developer github.com/gardener/cloud-provider-aws $d451e4ca38fcb67bfa9c355f605039619c136c9e
The alpine version has been updated to `v3.15.4`.
```
```improvement developer github.com/gardener/cloud-provider-aws $d451e4ca38fcb67bfa9c355f605039619c136c9e
The Golang version has been updated to `v1.16.15`.
```
```feature dependency github.com/gardener/cloud-provider-aws $a8cb9b6b1aba4dd8630daecfee2647aa0ea0069d
`k8s.io/legacy-cloud-providers` is now updated to `v1.22.9`.
```
```improvement developer github.com/gardener/cloud-provider-aws $9a33c6496ef4b77cc1f93ea81084259765349d71
The alpine …
```
> Upgrade github.com/gardener/cloud-provider-aws

- charts/images.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/Chart.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/deployment.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/role.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/rolebinding.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/serviceaccount.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/templates/vpa.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/values.yaml
- charts/internal/seed-controlplane/requirements.yaml
- charts/internal/seed-controlplane/values.yaml
- charts/internal/shoot-system-components/charts/aws-custom-route-controller/Chart.yaml
- charts/internal/shoot-system-components/charts/aws-custom-route-controller/templates/clusterrole.yaml
- charts/internal/shoot-system-components/charts/aws-custom-route-controller/templates/clusterrolebinding.yaml
- charts/internal/shoot-system-components/requirements.yaml
- charts/internal/shoot-system-components/values.yaml
- docs/usage-as-end-user.md
- hack/api-reference/api.md
- pkg/apis/aws/types_controlplane.go
- pkg/apis/aws/v1alpha1/types_controlplane.go
- pkg/apis/aws/v1alpha1/zz_generated.conversion.go
- pkg/apis/aws/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/aws/zz_generated.deepcopy.go
- pkg/aws/types.go
- pkg/controller/controlplane/valuesprovider.go
- pkg/controller/controlplane/valuesprovider_test.go
/platform aws
This PR allows to enable the [custom routes controller](https://github.com/gardener/aws-custom-route-controller).
If enabled, it will add routes to the pod CIDRs for all nodes in the route tables for all zones.
To enable it, set in the shoot spec:
```yaml
spec:
provider:
controlPlaneConfig:
apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
kind: ControlPlaneConfig
cloudControllerManager:
useCustomRouteController: true
```
Fixes #
```feature operator
Add optional custom-route-controller
```
/cc @ScheererJ
> Add optional custom-route-controller

- charts/images.yaml
/platform aws
Fixes several CVEs
Fixes #
```other operator
Update EBS CSI driver to `v1.11.3`
```
> update ebs driver

- test/integration/infrastructure/infrastructure_test.go
/kind bug
/platform aws
After revendoring of gardener `v1.56.0` the priority class is necessary for the terraformer pod.
/invite @shafeeqes 
Fixes #
```other operator
```
> Fix infrastructure tests after gardener v1.56.0

- docs/tutorials/kubernetes-cluster-on-aws-with-gardener/kubernetes-cluster-on-aws-with-gardener.md
/platform aws
This PR updates the formatting in the "Create a Kubernetes Cluster on AWS with Gardener" guide
Fixes #
```doc developer
NONE
```
> Updated the guide on creating a cluster

- pkg/admission/mutator/shoot.go
/kind bug
/platform aws
add nil pointer check
Fixes #
```other operator
none
```
> add nil pointer check

- charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
/platform aws
Improve logging for csi-driver-node to log mount operation details.
Fixes #418
```other operator
Improve logging for csi-driver-node to provide mount operation details.
```
> Improve logging for csi-driver-node

- charts/images.yaml
/platform aws
Update CSI version containing security improvements.
Fixes #
```other operator
Update github.com/kubernetes-sigs/aws-ebs-csi-driver to `v1.14.0`
```
> Update csi version

- .test-defs/bastion-test.yaml
- .test-defs/dnsrecord-test.yaml
- .test-defs/infrastructure-test.yaml
- .test-defs/provider-aws.yaml
- Dockerfile
/platform aws
Update golang to v1.19.4
```other operator
Update golang to 1.19.4
```
> Update golang to v1.19.4

- pkg/controller/bastion/options.go
/kind task
/platform aws
As AMI Image changed to arm64 processor Architecture `gardenlinux-aws-gardener_prod-arm64` , the original `t2.nano` with x86_64 is not supported. add a new instance type `t4g.nano` with arm64 architecture
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/694
```other operator
add an extra t4g.nano(arm64) processor architecture bastion instance to support for linux/arm64
```
> fix arm64 type for bastion instance

- pkg/controller/bastion/options.go
Reverts gardener/gardener-extension-provider-aws#700
Because bastion tests failed
> Revert "fix arm64 type for bastion instance"

- test/integration/bastion/bastion_test.go
/kind test
/platform aws
Fixes #
```other operator
Update bastion integration test AMI image
```
> Update bastion image AMI

- charts/internal/shoot-system-components/charts/aws-custom-route-controller/templates/role.yaml
/kind bug
/platform aws
Allow patching events for aws-custom-route-controller.
This fixes a reported issue:
```
'events "aws-custom-route-controller.175b5c88ae28dbac" is forbidden: User "system:serviceaccount:kube-system:aws-custom-route-controller" cannot patch resource "events" in API group "" in the namespace "kube-system"' (will not retry!)
```
Fixes https://github.com/gardener/gardener-extension-provider-aws/issues/734
```bugfix operator
Allow patching events for aws-custom-route-controller
```
> Allow patching events for aws-custom-route-controller

- .test-defs/bastion-test.yaml
- .test-defs/dnsrecord-test.yaml
- .test-defs/infrastructure-test.yaml
- .test-defs/provider-aws.yaml
- Dockerfile
- go.mod
/platform aws
Fixes #
```other operator
Update go to `v1.20.4`
```
> update go v1.20.4

- charts/internal/machine-controller-manager/seed/values.yaml
- charts/internal/seed-controlplane/charts/aws-custom-route-controller/values.yaml
- charts/internal/seed-controlplane/charts/aws-load-balancer-controller/values.yaml
- charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
- charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
/platform aws
Fixes #
```other operator
Remove limits from system critical components
```
> remove limits from system critical components

- go.mod
- go.sum
- vendor/github.com/gardener/gardener/hack/tools.mk
- vendor/modules.txt
/kind cleanup
/platform aws
The PR addresses a TODO introduced with https://github.com/gardener/gardener-extension-provider-aws/pull/801
N/A
N/A
```other operator
NONE
```
> Vendor gardener/gardener@v1.77.5

- imagevector/images.yaml
/platform aws
Fixes #
```other operator
updated image aws-load-balancer-controller -> `v2.6.1`
```
```other operator
updated image aws-ebs-csi-driver -> `v1.23.0`
```
```other operator
updated image csi-provisioner -> `v3.6.0`
```
```other operator
updated image csi-attacher -> `v4.4.0`
```
```other operator
updated image csi-resizer -> `v1.9.0`
```
```other operator
updated image snapshot-controller -> `v6.3.0`
```
```other operator
updated image livenessprobe -> `v2.11.0`
```
> update image definitions

- charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-deployment.yaml
/platform aws
Fixes #
```other operator
Add readiness check for snapshot validation webhook.
```
> add readiness check

- charts/internal/shoot-system-components/charts/aws-load-balancer-controller/templates/helpers.tpl
- charts/internal/shoot-system-components/charts/aws-load-balancer-controller/values.yaml
/kind technical-debt
/platform aws
Symlinks do not work in charts after latest gardener revendoring. This PR removes the symlinks in the ALBC.
Fixes #
```other operator
NONE
```
> fix symlinked charts

- docs/usage/dual-stack-ingress.md
/platform aws
Add Documentation about IPv4/IPv6 (dual-stack) Ingress Usage.
None.
```other operator
```
/cc @axel7born @DockToFuture
> Add Documentation about IPv4/IPv6 (dual-stack) Ingress Usage

- go.mod
- go.sum
- vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
- vendor/github.com/gardener/gardener/hack/kind-up.sh
- vendor/modules.txt
/kind bug
/platform aws
This PR vendors github.com/gardener/gardener@v1.83.3 in order to adopt cherry-pick of https://github.com/gardener/gardener/pull/8943.
N/A
N/A
```other operator
The following dependency is updated to adopt a cherry-pick of https://github.com/gardener/gardener/pull/8943:
- github.com/gardener/gardener: v1.83.2 -> v1.83.3
```
> Vendor gardener/gardener@v1.83.3

- go.mod
- go.sum
- vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
- vendor/github.com/gardener/gardener/hack/kind-up.sh
- vendor/modules.txt
/kind bug
Cherry pick of #842 on release-v1.51.
#842: Vendor gardener/gardener@v1.83.3
```other operator
The following dependency is updated to adopt a cherry-pick of https://github.com/gardener/gardener/pull/8943:
- github.com/gardener/gardener: v1.83.2 -> v1.83.3
```
> [release-v1.51] Automated cherry pick of #842: Vendor gardener/gardener@v1.83.3

- charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
- imagevector/images.yaml
/platform aws
Fixes #
```dependency user
Updated csi-attacher configuration. The timeout for the attach/detach operations has been increased to 1 minute (from the default of 15 seconds) and the maximum wait period between retries has been reduced to 3 minutes (from the default of 5).
```
```dependency user
Updated aws-ebs-csi-driver -> v1.26.1
```
```dependency user
Updated volume-modifier-for-k8s -> v0.1.3
```
> update ebs driver and configuration

- Makefile
/platform aws
Fixes #
```other operator
NONE
```
> Update image build rules

- imagevector/images.yaml
/platform aws
Fixes #
```dependency operator
Update cloud-controller-manager image "v1.25.3" -> "v1.25.14"
```
```dependency operator
Update cloud-controller-manager image "v1.26.1" -> "v1.26.10"
```
```dependency operator
Update cloud-controller-manager image "v1.27.1" -> "v1.27.5"
```
```dependency operator
Update cloud-controller-manager image "v1.28.1" -> "v1.28.4"
```
> update ccm images

- Makefile
/platform aws
Fixes #
```other operator
NONE
```
> fix Makefile flag

- .ci/hack/set_dependency_version
- example/20-crd-extensions.gardener.cloud_infrastructures.yaml
- go.mod
- go.sum
- pkg/controller/infrastructure/actuator_reconcile.go
- pkg/controller/infrastructure/actuator_restore.go
/platform aws
Fixes #
```other operator
provider-aws will calculate a shoot's Egress CIDRs on infrastructure reconciliation. 
```
> add nat-gateway ips

- Makefile
/platform aws
Adapt make start with correct env variables.
Fixes #
```other operator
NONE
```
> fix make start

- pkg/controller/infrastructure/actuator_reconcile.go
- pkg/controller/infrastructure/infraflow/context.go
- pkg/controller/infrastructure/infraflow/reconcile.go
- test/integration/infrastructure/infrastructure_test.go
/platform aws
Fixes #
```other operator
```
> fix ipv6 conditions for existing vpc

- charts/gardener-extension-admission-aws/charts/runtime/templates/deployment.yaml
/kind bug
/platform aws
Necessary for https://github.com/gardener/gardener/pull/9168
Fixes #
```other operator
Admission controller will be deployed with the LEADER_ELECTION_NAMESPACE set to the pod namespace
```
> specify leader-election ns

- imagevector/images.yaml
```other operator
Update terraformer to v2.25.0
```
> Upgrade terraformer in v1.52

- docs/usage/usage.md
/platform aws
Fixes #
```other operator
```
> improve worker docs

- pkg/controller/worker/machines.go
- pkg/controller/worker/machines_test.go
/platform aws
Fixes #
```breaking users
Shoots created on or upgrading into kubernetes v1.30 and above, will have their worker pool using IMDSv2 by default. Users whose workload is affected and cannot work with IMDSv2 should opt-out by specifying so in their worker pool's configuration.
```
> Enforce the usage of imdsv2 on k8s v1.30

- pkg/controller/infrastructure/infraflow/context.go
/kind bug
/platform aws
Fixes #
```other operator
Fix a segmentation fault error when trying to delete the infrastructure with the flow reconciler if the VPC has not been successfully created.
```
> fix nil pointer vpc deletion

- example/20-crd-vpa.yaml
/area testing
/kind technical-debt
/platform aws
Fixes #
```other operator
Update the VPA CRD used for testing locally
```
> update vpa crd

- pkg/controller/dnsrecord/actuator.go
/area monitoring
/platform aws
This PR fixes the error classification when deleting DNS record sets.
Fixes #1032
```other operator
Fix error classification when deleting DNS record sets
```
> Determine user error in DeleteDNSRecordSet

- pkg/controller/infrastructure/terraform.go
/area quality
/kind bug
Cherry pick of #1034 on release-v1.57.
#1034: Fix error handling
> [release-v1.57] Automated cherry pick of #1034: Fix error handling

- .test-defs/apply-flow-aws.yaml
- test/tm/apply_flow/maintain_test.go
- test/tm/apply_flow/shoot_maintain_suite_test.go
/kind test
/platform aws
Fixes #
```other operator
Add flow migration integration test
```
> add flow migration test

- docs/usage/dual-stack-ingress.md
/platform aws
Extend dual-stack documentation concerning DNS considerations.
Fixes #
```other operator
```
/invite @axel7born @MartinWeindel
> Extend dual-stack documentation concerning DNS considerations

- .test-defs/infrastructure-test.yaml
- test/integration/infrastructure/infrastructure_test.go
/area testing
/platform aws
Fixes #
```other operator
NONE
```
> parallel infrastructure tests

- imagevector/images.yaml
/platform aws
Fixes #
```other operator
NONE
```
> downgrade unpublished images

- .test-defs/apply-flow-aws.yaml
- .test-defs/bastion-test.yaml
- .test-defs/dnsrecord-test.yaml
- .test-defs/infrastructure-test.yaml
- .test-defs/provider-aws.yaml
- Dockerfile
- go.mod
/area quality
/platform aws
Update to go 1.23.3
Fixes #
```other dependency
Update go to version 1.23.3
```
> Update to go 1.23.3

- docs/usage/usage.md
/kind docs
/platform aws
Fixes #
```other operator
```
> Add section on internal load balancer config to usage docs.

- Makefile
- pkg/apis/aws/validation/shoot.go
- pkg/apis/config/loader/loader.go
- pkg/aws/types.go
- pkg/controller/infrastructure/infraflow/reconcile.go
- pkg/controller/worker/machines.go
- pkg/webhook/controlplane/ensurer.go
/area quality
/platform aws
Add gosec as sast makefile target
Fixes #
```other developer
Add gosec as sast makefile target
```
> Introduce gosec 

- .test-defs/apply-flow-aws.yaml
- .test-defs/bastion-test.yaml
- .test-defs/dnsrecord-test.yaml
- .test-defs/infrastructure-test.yaml
- .test-defs/provider-aws.yaml
- Dockerfile
- go.mod
/area quality
/platform aws
Update golang versions
Fixes #
```other operator
NONE
```
> Update golang versions

- pkg/controller/controlplane/valuesprovider.go
- pkg/controller/infrastructure/flow_reconciler.go
- pkg/controller/infrastructure/infraflow/context.go
- pkg/controller/infrastructure/infraflow/reconcile.go
- pkg/controller/infrastructure/templates/main.tpl.tf
- pkg/controller/infrastructure/tf_reconciler.go
- test/integration/infrastructure/infrastructure_test.go
/platform aws
Fixes #
```other operator
Add IPv4 ranges from Spec.Networking to Status.Networking.
```
> Add IPv4 ranges from Spec.Networking to Status.Networking.

- docs/usage/usage.md
/platform aws
Add IPv6 shoot manifest to docs.
Fixes #1134
```other operator
none
```
> add ipv6 shoot manifest to docs

- pkg/controller/controlplane/valuesprovider.go
- pkg/controller/controlplane/valuesprovider_test.go
/kind bug
/platform aws
Fixes #
```other operator
Filter pod ranges for IPv4 CIDRs to configure Custom-Route-Controller.
```
> Filter pod ranges for IPv4 CIDRs to configure Custom-Route-Controller.

- docs/usage/ipv6.md
- docs/usage/usage.md
/platform aws
Add overview documentation for IPv6.
Fixes #
```doc user
Add overview documentation for IPv6
```
> Add overview documentation for IPv6

- pkg/controller/controlplane/valuesprovider.go
- pkg/controller/controlplane/valuesprovider_test.go
/kind cleanup
/platform aws
Fixes #
```other operator
```
> Cleanup snapshot-validation leftovers

- charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
/platform aws
Fixes #
```other operator
Update CSI container kube-api-* and worker arguments according to upstream recommendations. 
```
> update csi container args according to upstream

- charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-deployment.yaml
/area TODO
/kind TODO
/platform aws
Fixes #
```other operator
NONE
```
> fix incorrect arg in csi driver

- charts/internal/seed-controlplane/charts/aws-ipam-controller/templates/role.yaml
/platform aws
Use minimal permissions for `aws-ipam-controller`.
Fixes #
```other operator
Use minimal permissions for `aws-ipam-controller`.
```
> use minimal permissions for aws-ipam-controller

- imagevector/images.yaml
/platform aws
Fixes #
```other operator
Update csi driver to latest version v1.43.0
```
> update csi image to latest

- pkg/aws/client/client.go
- pkg/aws/client/filter.go
- pkg/aws/client/filter_test.go
- pkg/aws/client/tags.go
- pkg/controller/bastion/actuator_reconcile.go
- test/integration/bastion/bastion_test.go
- test/integration/infrastructure/infrastructure_test.go
- test/integration/route.go
- test/integration/vpc.go
/platform aws
This PR is adding client filter unit tests.
Fixes #
```other operator
NONE
```
> Add client filter unit tests

- .github/workflows/build.yaml
- .github/workflows/head-update.yaml
/area TODO
/kind TODO
/platform aws
Fixes #
```other operator
```
> publish component-descriptor for head-update-jobs

- .github/workflows/head-update.yaml
/area delivery
/kind cleanup
/platform aws
Fixes #
```other operator
```
> GH Actions Cleanup

- .ci/testruns/default/templates/testrun.yaml
- .test-defs/apply-flow-aws.yaml
- .test-defs/backupbucket-test.yaml
- .test-defs/bastion-test.yaml
- .test-defs/dnsrecord-test.yaml
- .test-defs/infrastructure-test.yaml
- .test-defs/provider-aws.yaml
- Makefile
- test/integration/backupbucket/backupbucket_suite_test.go
- test/integration/backupbucket/backupbucket_test.go
- test/integration/backupbucket/helper_test.go
/area testing
/kind test
/platform aws
adds integration test for backupbuckets
Fixes #
> add backupbucket integration test

- .ocm/base-component.yaml
/area delivery
/kind bug
/platform aws
Fixes #
```other developer
fix: declare alpine and pause-images in ocm-component-descriptor
```
> fix: declare alpine and pause-images in ocm-component-descriptor

- imagevector/images.yaml
/platform aws
Update `aws-ipam-controller` to `v0.6.0`.
Fixes #
```other operator
Update `aws-ipam-controller` to `v0.6.0`.
```
> update aws-ipam-controller to v0.6.0

- .github/workflows/release.yaml
- .github/workflows/run-integrationtests.yaml
/area delivery
/kind bug
/platform aws
Fixes #
```other developer
run integrationtests (again) as part of release
```
> run integrationtests (again) as part of release

- .ocm/base-component.yaml
/area TODO
/kind TODO
/platform aws
Fixes #
```other operator
NONE
```
> set base component descriptor explicitly

- pkg/controller/bastion/actuator.go
- pkg/controller/bastion/actuator_delete.go
- pkg/controller/bastion/actuator_reconcile.go
- pkg/controller/bastion/options.go
- test/integration/bastion/bastion_test.go
/area quality
/platform aws
Separate bastion reconcile and delete options
Fixes #
```other developer
Separate bastion reconcile and delete options
```
> Separate bastion reconcile and delete options

- Makefile
- charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
- charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
- docs/usage/usage.md
- pkg/aws/types.go
- pkg/controller/controlplane/valuesprovider.go
/platform aws
Fixes #
```other operator
Support the reserved-volume-attachments flag for the EBS CSI driver.
```
> support reserved volume attachments

- .github/workflows/head-update.yaml
- .github/workflows/release.yaml
- .ocm/base-component.yaml
/area TODO
/kind TODO
/platform aws
Fixes #
```other operator
```
> Fix GHA (missing privileges + typo in workflow name)

- charts/internal/shoot-crds/charts/aws-load-balancer-controller/templates/crd-ingressclassparams.yaml
- imagevector/images.yaml
/area quality
/platform aws
Update dependency images
Fixes #
https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.13.3
```other operator
Update aws-load-balancer-controller from v2.11.0 to v2.13.3
```
```other operator
Update csi-driver from v1.43.0 to v1.47.0
```
```other operator
Update csi-snapshotter from v8.2.1 to v8.3.0
```
```other operator
Update csi-snapshot-controller from v8.2.1 to v8.3.0
```
```other operator
Update csi-node-driver-registrar from v2.13.0 to v2.14.0
```
```other operator
Update csi-liveness-probe from v2.15.0 to v2.16.0
```
```other operator
Update …
```
> `chore:` Update images

- docs/usage/dual-stack-ingress.md
/area docs
/kind networking
/platform aws
During the migration of load balancers to dual-stack, new load balancers are created while old load balancers still exist.
Added a section to the docs, to make users aware of that fact.
Fixes #
```other operator
None
```
> Add notes regarding quotas to dual-stack ingress docs.

- .github/workflows/run-integrationtests.yaml
/area TODO
/kind TODO
/platform aws
Fixes #
```other operator
NONE
```
> add fixes for gha integration tests

- docs/usage/usage.md
/area quality
/platform aws
Fixes #
```other operator
NONE
```
> Improve Load Balancer usage docu

- imagevector/images.yaml
/platform aws
Update aws-ipam-controller to `v0.7.0`. See: https://github.com/gardener/aws-ipam-controller/releases/tag/v0.7.0
Fixes #
```other operator
Update aws-ipam-controller to `v0.7.0`.
```
> update aws-ipam-controller to v0.7.0
